# -*- coding: utf-8 -*-
from catalog_i18n import T
COUNTRY = {
 "Spain":T("Spain","España","إسبانيا","西班牙"),
 "Austria":T("Austria","Austria","النمسا","奥地利"),
 "Costa Rica":T("Costa Rica","Costa Rica","كوستاريكا","哥斯达黎加"),
 "Switzerland":T("Switzerland","Suiza","سويسرا","瑞士"),
 "Portugal":T("Portugal","Portugal","البرتغال","葡萄牙"),
 "Mexico":T("Mexico","México","المكسيك","墨西哥"),
 "Greece":T("Greece","Grecia","اليونان","希腊"),
 "France":T("France","Francia","فرنسا","法国"),
 "Indonesia":T("Indonesia","Indonesia","إندونيسيا","印度尼西亚"),
 "Argentina":T("Argentina","Argentina","الأرجنتين","阿根廷"),
 "Thailand":T("Thailand","Tailandia","تايلاند","泰国"),
 "United States":T("United States","Estados Unidos","الولايات المتحدة","美国"),
 "United Kingdom":T("United Kingdom","Reino Unido","المملكة المتحدة","英国"),
 "Italy":T("Italy","Italia","إيطاليا","意大利"),
 "Dominican Republic":T("Dominican Republic","República Dominicana","جمهورية الدومينيكان","多米尼加共和国"),
 "Germany":T("Germany","Alemania","ألمانيا","德国"),
 "Colombia":T("Colombia","Colombia","كولومبيا","哥伦比亚"),
 "Guatemala":T("Guatemala","Guatemala","غواتيمالا","危地马拉"),
 "Chile":T("Chile","Chile","تشيلي","智利"),
 "Ireland":T("Ireland","Irlanda","أيرلندا","爱尔兰"),
 "Brazil":T("Brazil","Brasil","البرازيل","巴西"),
 "United Arab Emirates":T("United Arab Emirates","Emiratos Árabes Unidos","الإمارات العربية المتحدة","阿联酋"),
 "Bahamas":T("Bahamas","Bahamas","جزر البهاما","巴哈马"),
 "Saint Barthélemy":T("Saint Barthélemy","San Bartolomé","سان بارتيلمي","圣巴泰勒米"),
 "Panama":T("Panama","Panamá","بنما","巴拿马"),
 "Belize":T("Belize","Belice","بليز","伯利兹"),
 "Morocco":T("Morocco","Marruecos","المغرب","摩洛哥"),
 "Maldives":T("Maldives","Maldivas","جزر المالديف","马尔代夫"),
 "Singapore":T("Singapore","Singapur","سنغافورة","新加坡"),
 "Turkey":T("Turkey","Turquía","تركيا","土耳其"),
 "Uruguay":T("Uruguay","Uruguay","أوروغواي","乌拉圭"),
}
CITY = {
 "Barcelona":T("Barcelona","Barcelona","برشلونة","巴塞罗那"),
 "Lech":T("Lech","Lech","ليش","莱希"),
 "Nosara":T("Nosara","Nosara","نوسارا","诺萨拉"),
 "Weggis":T("Weggis","Weggis","فيغيس","韦吉斯"),
 "Quinta do Lago":T("Quinta do Lago","Quinta do Lago","كينتا دو لاغو","金塔杜拉戈"),
 "San José del Cabo":T("San José del Cabo","San José del Cabo","سان خوسيه ديل كابو","圣何塞德尔卡沃"),
 "Paros":T("Paros","Paros","باروس","帕罗斯"),
 "Megève":T("Megève","Megève","ميجيف","梅杰夫"),
 "Ibiza":T("Ibiza","Ibiza","إيبيزا","伊维萨"),
 "Ubud":T("Ubud","Ubud","أوبود","乌布"),
 "Buenos Aires":T("Buenos Aires","Buenos Aires","بوينس آيرس","布宜诺斯艾利斯"),
 "Phuket":T("Phuket","Phuket","بوكيت","普吉"),
 "Miami Beach":T("Miami Beach","Miami Beach","ميامي بيتش","迈阿密海滩"),
 "Miami":T("Miami","Miami","ميامي","迈阿密"),
 "London":T("London","Londres","لندن","伦敦"),
 "Portofino":T("Portofino","Portofino","بورتوفينو","波托菲诺"),
 "Punta Cana":T("Punta Cana","Punta Cana","بونتا كانا","蓬塔卡纳"),
 "Venice":T("Venice","Venecia","البندقية","威尼斯"),
 "Ciudad de México":T("Mexico City","Ciudad de México","مدينة مكسيكو","墨西哥城"),
 "Carcassonne":T("Carcassonne","Carcasona","كاركاسون","卡尔卡松"),
 "Amboise":T("Amboise","Amboise","أمبواز","昂布瓦兹"),
 "Füssen":T("Füssen","Füssen","فوسن","菲森"),
 "Montalcino":T("Montalcino","Montalcino","مونتالتشينو","蒙塔尔奇诺"),
 "Segovia":T("Segovia","Segovia","سيغوفيا","塞哥维亚"),
 "Évora":T("Évora","Évora","إيفورا","埃武拉"),
 "Mérida":T("Mérida","Mérida","ميريدا","梅里达"),
 "Salento":T("Salento","Salento","سالينتو","萨伦托"),
 "Jerez":T("Jerez","Jerez","خيريث","赫雷斯"),
 "Antigua":T("Antigua","Antigua","أنتيغوا","安提瓜"),
 "Casablanca":T("Casablanca","Casablanca","كازابلانكا","卡萨布兰卡"),
 "Las Terrenas":T("Las Terrenas","Las Terrenas","لاس تيريناس","拉斯特雷纳斯"),
 "Wicklow":T("Wicklow","Wicklow","ويكلو","威克洛"),
 "Klosters":T("Klosters","Klosters","كلوسترز","克洛斯特斯"),
 "Perthshire":T("Perthshire","Perthshire","بيرثشاير","珀斯郡"),
 "Ostuni":T("Ostuni","Ostuni","أوستوني","奥斯图尼"),
 "Aix-en-Provence":T("Aix-en-Provence","Aix-en-Provence","إكس أن بروفانس","普罗旺斯艾克斯"),
 "Trancoso":T("Trancoso","Trancoso","ترانكوسو","特兰科苏"),
 "Dubai":T("Dubai","Dubái","دبي","迪拜"),
 "Rome":T("Rome","Roma","روما","罗马"),
 "Puerto Escondido":T("Puerto Escondido","Puerto Escondido","بويرتو إسكونديدو","埃斯孔迪多港"),
 "Lagos":T("Lagos","Lagos","لاغوس","拉古什"),
 "Great Exuma":T("Great Exuma","Gran Exuma","غريت إكزوما","大埃克苏马"),
 "Gustavia":T("Gustavia","Gustavia","غوستافيا","古斯塔维亚"),
 "Saint-Jean-Cap-Ferrat":T("Saint-Jean-Cap-Ferrat","Saint-Jean-Cap-Ferrat","سان جان كاب فيرا","圣让卡弗尔拉"),
 "Uluwatu":T("Uluwatu","Uluwatu","أولواتو","乌鲁瓦图"),
 "Newmarket":T("Newmarket","Newmarket","نيوماركت","纽马基特"),
 "Seville":T("Seville","Sevilla","إشبيلية","塞维利亚"),
 "Deauville":T("Deauville","Deauville","دوفيل","多维尔"),
 "Guadalajara":T("Guadalajara","Guadalajara","غوادالاخارا","瓜达拉哈拉"),
 "Pilar":T("Pilar","Pilar","بيلار","皮拉尔"),
 "Estremoz":T("Estremoz","Estremoz","إستريموز","埃斯特雷莫斯"),
 "Exuma Cays":T("Exuma Cays","Cayos de Exuma","جزر إكزوما","埃克苏马群岛"),
 "Aeolian Islands":T("Aeolian Islands","Islas Eolias","جزر إيولي","伊奥利亚群岛"),
 "Raja Ampat":T("Raja Ampat","Raja Ampat","راجا أمبات","四王群岛"),
 "Placencia":T("Placencia","Placencia","بلاسينسيا","普拉森西亚"),
 "Samaná Bay":T("Samaná Bay","Bahía de Samaná","خليج سامانا","萨马纳湾"),
 "Guna Yala":T("Guna Yala","Guna Yala","غونا يالا","库纳雅拉"),
}
def loc(name, lang, table):
    e = table.get(name)
    return e[lang] if e else name

CITY.update({
 "Abu Dhabi":T("Abu Dhabi","Abu Dabi","أبوظبي","阿布扎比"),
 "Aegean":T("Aegean","Egeo","بحر إيجه","爱琴海"),
 "Arraiján":T("Arraiján","Arraiján","أرايخان","阿拉伊汉"),
 "Baa Atoll":T("Baa Atoll","Atolón de Baa","جزيرة با المرجانية","芭环礁"),
 "Batam":T("Batam","Batam","باتام","巴淡"),
 "Belize City":T("Belize City","Ciudad de Belice","مدينة بليز","伯利兹城"),
 "Benidorm":T("Benidorm","Benidorm","بنيدورم","贝尼多姆"),
 "Birmingham":T("Birmingham","Birmingham","برمنغهام","伯明翰"),
 "Bocas del Toro":T("Bocas del Toro","Bocas del Toro","بوكاس ديل تورو","博卡斯德尔托罗"),
 "Bodrum":T("Bodrum","Bodrum","بودروم","博德鲁姆"),
 "Bogotá":T("Bogotá","Bogotá","بوغوتا","波哥大"),
 "Cancún":T("Cancún","Cancún","كانكون","坎昆"),
 "Cap Cana":T("Cap Cana","Cap Cana","كاب كانا","卡普卡纳"),
 "Culiacán":T("Culiacán","Culiacán","كولياكان","库利亚坎"),
 "Durazno":T("Durazno","Durazno","دورازنو","杜拉斯诺"),
 "Edinburgh":T("Edinburgh","Edimburgo","إدنبرة","爱丁堡"),
 "Exuma":T("Exuma","Exuma","إكزوما","埃克苏马"),
 "Haro":T("Haro","Haro","هارو","阿罗"),
 "Huatulco":T("Huatulco","Huatulco","هواتولكو","瓦图尔科"),
 "Huelva":T("Huelva","Huelva","ويلبا","韦尔瓦"),
 "Ilhéus":T("Ilhéus","Ilhéus","إلياوس","伊列乌斯"),
 "Jaén":T("Jaén","Jaén","خاين","哈恩"),
 "Kitzbühel":T("Kitzbühel","Kitzbühel","كيتسبوهيل","基茨比厄尔"),
 "Krabi":T("Krabi","Krabi","كرابي","甲米"),
 "La Fortuna":T("La Fortuna","La Fortuna","لا فورتونا","拉福图纳"),
 "Lake Como":T("Lake Como","Lago de Como","بحيرة كومو","科莫湖"),
 "Liberia":T("Liberia","Liberia","ليبيريا","利比里亚"),
 "Lisbon":T("Lisbon","Lisboa","لشبونة","里斯本"),
 "Liverpool":T("Liverpool","Liverpool","ليفربول","利物浦"),
 "Madrid":T("Madrid","Madrid","مدريد","马德里"),
 "Manchester":T("Manchester","Mánchester","مانشستر","曼彻斯特"),
 "Marbella":T("Marbella","Marbella","ماربيا","马贝拉"),
 "Marmaris":T("Marmaris","Marmaris","مرمريس","马尔马里斯"),
 "Marrakech":T("Marrakech","Marrakech","مراكش","马拉喀什"),
 "Mendoza":T("Mendoza","Mendoza","مندوزا","门多萨"),
 "Miches":T("Miches","Miches","ميتشيس","米切斯"),
 "Monterrey":T("Monterrey","Monterrey","مونتيري","蒙特雷"),
 "Munich":T("Munich","Múnich","ميونخ","慕尼黑"),
 "Mykonos":T("Mykonos","Míconos","ميكونوس","米科诺斯"),
 "Málaga":T("Málaga","Málaga","مالقة","马拉加"),
 "Naples":T("Naples","Nápoles","نابولي","那不勒斯"),
 "Nassau":T("Nassau","Nassau","ناساو","拿骚"),
 "Nazaré":T("Nazaré","Nazaré","نازاريه","纳扎雷"),
 "Neiva":T("Neiva","Neiva","نيفا","内瓦"),
 "Oaxaca de Juárez":T("Oaxaca","Oaxaca","واهاكا","瓦哈卡"),
 "Osa":T("Osa","Osa","أوسا","奥萨"),
 "Panama City":T("Panama City","Ciudad de Panamá","مدينة بنما","巴拿马城"),
 "Porto":T("Porto","Oporto","بورتو","波尔图"),
 "Puerto Plata":T("Puerto Plata","Puerto Plata","بويرتو بلاتا","银港"),
 "Puerto Varas":T("Puerto Varas","Puerto Varas","بويرتو باراس","巴拉斯港"),
 "Punta Mita":T("Punta Mita","Punta Mita","بونتا ميتا","蓬塔米塔"),
 "Riviera Maya":T("Riviera Maya","Riviera Maya","ريفييرا مايا","玛雅海岸"),
 "Sagres":T("Sagres","Sagres","ساغريس","萨格里什"),
 "Samaná":T("Samaná","Samaná","سامانا","萨马纳"),
 "San Blas":T("San Blas","San Blas","سان بلاس","圣布拉斯"),
 "Santorini":T("Santorini","Santorini","سانتوريني","圣托里尼"),
 "Silves":T("Silves","Silves","سيلفيش","锡尔维什"),
 "Singapore":T("Singapore","Singapur","سنغافورة","新加坡"),
 "Tignes":T("Tignes","Tignes","تين","蒂涅"),
 "Tulum":T("Tulum","Tulum","تولوم","图卢姆"),
 "Vilamoura":T("Vilamoura","Vilamoura","فيلامورا","维拉莫拉"),
})

# ---- frases de uso, acceso y rasgo distintivo (traducción por fragmentos) ----
_W = {
 # usos
 "Resort / residential":T("Resort / residential","Resort / residencial","منتجع / سكني","度假村／住宅"),
 "Boutique resort":T("Boutique resort","Resort boutique","منتجع بوتيك","精品度假村"),
 "Integrated resort":T("Integrated resort","Resort integrado","منتجع متكامل","综合度假村"),
 "Mixed resort":T("Mixed resort","Resort mixto","منتجع مختلط","混合度假村"),
 "Low-density resort":T("Low-density resort","Resort de baja densidad","منتجع منخفض الكثافة","低密度度假村"),
 "Eco-resort":T("Eco-resort","Eco-resort","منتجع بيئي","生态度假村"),
 "Hotel, up to 320 keys":T("Hotel, up to 320 keys","Hotel, hasta 320 llaves","فندق حتى 320 مفتاحاً","酒店，最多 320 间客房"),
 "Resort, up to 180 keys":T("Resort, up to 180 keys","Resort, hasta 180 llaves","منتجع حتى 180 مفتاحاً","度假村，最多 180 间客房"),
 "Boutique hotel":T("Boutique hotel","Hotel boutique","فندق بوتيك","精品酒店"),
 "Mountain resort":T("Mountain resort","Resort de montaña","منتجع جبلي","山地度假村"),
 "Desert resort":T("Desert resort","Resort de desierto","منتجع صحراوي","沙漠度假村"),
 "Golf resort":T("Golf resort","Resort de golf","منتجع غولف","高尔夫度假村"),
 "Master-planned town":T("Master-planned town","Ciudad con plan maestro","مدينة مخططة","总体规划新城"),
 "Coastal masterplan":T("Coastal masterplan","Masterplan costero","مخطط ساحلي شامل","海岸总体规划"),
 "Resort district":T("Resort district","Distrito turístico","حي منتجعات","度假区"),
 "Eco masterplan":T("Eco masterplan","Masterplan ecológico","مخطط بيئي شامل","生态总体规划"),
 "Island masterplan":T("Island masterplan","Masterplan insular","مخطط جزري شامل","岛屿总体规划"),
 "Logistics masterplan":T("Logistics masterplan","Masterplan logístico","مخطط لوجستي شامل","物流总体规划"),
 "Mixed use":T("Mixed use","Uso mixto","استخدام مختلط","综合用途"),
 "Waterfront mixed":T("Waterfront mixed","Uso mixto en frente marítimo","مختلط على الواجهة المائية","滨水综合用途"),
 "Transit-oriented":T("Transit-oriented","Orientado al transporte","موجّه للنقل","公交导向开发"),
 "Business district":T("Business district","Distrito de negocios","حي أعمال","商务区"),
 "Urban regeneration":T("Urban regeneration","Regeneración urbana","تجديد حضري","城市更新"),
 "Residential growth":T("Residential growth","Crecimiento residencial","نمو سكني","住宅增长"),
 "Vineyard estate":T("Vineyard estate","Finca con viñedo","ضيعة كروم","葡萄园地产"),
 "Olive estate":T("Olive estate","Finca de olivar","ضيعة زيتون","橄榄园地产"),
 "Coffee estate":T("Coffee estate","Finca cafetera","ضيعة بنّ","咖啡庄园"),
 "Cattle estate":T("Cattle estate","Estancia ganadera","ضيعة ماشية","牧场地产"),
 "Agroforestry":T("Agroforestry","Agroforestal","زراعة حرجية","农林复合"),
 "Irrigated cropland":T("Irrigated cropland","Cultivo de regadío","أراضٍ مروية","灌溉农田"),
 "Undeveloped island":T("Undeveloped island","Isla sin desarrollar","جزيرة غير مطوَّرة","未开发岛屿"),
 "Island group":T("Island group","Grupo insular","مجموعة جزر","岛屿群"),
 "Lagoon island":T("Lagoon island","Isla de laguna","جزيرة بحيرية","潟湖岛"),
 "Reef island":T("Reef island","Isla de arrecife","جزيرة مرجانية","珊瑚礁岛"),
 "Volcanic island":T("Volcanic island","Isla volcánica","جزيرة بركانية","火山岛"),
 "Protected coastal":T("Protected coastal","Costa protegida","ساحل محمي","受保护海岸"),
}
def phrase(txt, lang):
    e=_W.get(txt)
    return e[lang] if e else txt

_W.update({
 "A-44 motorway":T("A-44 motorway","Autovía A-44","الطريق السريع A-44","A-44 高速公路"),
 "A22 motorway":T("A22 motorway","Autopista A22","الطريق السريع A22","A22 高速公路"),
 "Autopista Norte":T("Autopista Norte","Autopista Norte","أوتوبيستا نورتي","北部高速"),
 "BR-101 + port":T("BR-101 and port","BR-101 y puerto","BR-101 والميناء","BR-101 与港口"),
 "Coastal highway":T("Coastal highway","Autopista costera","الطريق الساحلي السريع","滨海高速"),
 "Coastal road + marina":T("Coastal road and marina","Carretera costera y marina","الطريق الساحلي والمرسى","滨海公路与码头"),
 "Coastal road + marine":T("Coastal road and marine access","Carretera costera y acceso marítimo","الطريق الساحلي والوصول البحري","滨海公路与海路"),
 "E10 + metro corridor":T("E10 and metro corridor","E10 y corredor de metro","E10 وممر المترو","E10 与地铁走廊"),
 "E611 corridor":T("E611 corridor","Corredor E611","ممر E611","E611 走廊"),
 "Federal highway":T("Federal highway","Carretera federal","الطريق الاتحادي","联邦公路"),
 "Federal highway + rail":T("Federal highway and rail","Carretera federal y ferrocarril","الطريق الاتحادي والسكة الحديدية","联邦公路与铁路"),
 "Ferry + airstrip":T("Ferry and airstrip","Ferry y pista de aterrizaje","العبّارة ومهبط طائرات","渡轮与简易机场"),
 "Highway + 28 km airport":T("Highway, airport 28 km","Autopista, aeropuerto a 28 km","الطريق السريع، المطار على بعد 28 كم","高速公路，机场 28 公里"),
 "Highway 200 + airport":T("Highway 200 and airport","Carretera 200 y aeropuerto","الطريق 200 والمطار","200 号公路与机场"),
 "Marine + airstrip":T("Marine access and airstrip","Acceso marítimo y pista","الوصول البحري ومهبط طائرات","海路与简易机场"),
 "Marine access":T("Marine access","Acceso marítimo","وصول بحري","海路可达"),
 "Marine access only":T("Marine access only","Solo acceso marítimo","وصول بحري فقط","仅海路可达"),
 "Metro + arterial":T("Metro and arterial road","Metro y vía arterial","المترو وطريق رئيسي","地铁与主干道"),
 "Metro interchange":T("Metro interchange","Intercambiador de metro","تقاطع مترو","地铁换乘枢纽"),
 "Motorway + rail":T("Motorway and rail","Autopista y ferrocarril","الطريق السريع والسكة الحديدية","高速公路与铁路"),
 "National road":T("National road","Carretera nacional","الطريق الوطني","国道"),
 "National road frontage":T("National road frontage","Frente a carretera nacional","واجهة على الطريق الوطني","国道临路"),
 "Pan-American Highway":T("Pan-American Highway","Carretera Panamericana","الطريق السريع الأمريكي","泛美公路"),
 "Paved road + 42 km airport":T("Paved road, airport 42 km","Carretera asfaltada, aeropuerto a 42 km","طريق معبّد، المطار على بعد 42 كم","柏油公路，机场 42 公里"),
 "Provincial road":T("Provincial road","Carretera provincial","طريق إقليمي","省道"),
 "Ring road + port":T("Ring road and port","Ronda y puerto","الطريق الدائري والميناء","环路与港口"),
 "Route 21 + airport":T("Route 21 and airport","Ruta 21 y aeropuerto","الطريق 21 والمطار","21 号公路与机场"),
 "Route 5":T("Route 5","Ruta 5","الطريق 5","5 号公路"),
 "Route 5 + 34 km airport":T("Route 5, airport 34 km","Ruta 5, aeropuerto a 34 km","الطريق 5، المطار على بعد 34 كم","5 号公路，机场 34 公里"),
 "Ruta 40":T("Route 40","Ruta 40","الطريق 40","40 号公路"),
})
