# -*- coding: utf-8 -*-
"""XARU HOME — Phase 3 copy (development & capital core).
Real pillar copy for Project Structuring & Development and Capital & Strategic
Partnerships, the Capital door page, the Private Deal Room and the improved
two-way Submit intake — all in EN/ES/AR/ZH. Consumed by gen_i18n.py.
Rules: brand names never translated · Western figures · sober patrimonial tone ·
no unsupported regulatory claims ("through authorised entities and partners
where the activity requires it") · in Structuring never "XARU always develops" —
always the permitted formulation (adviser / structurer / integrator / sponsor /
development manager / strategic participant) · [PHASE 0] marks data pending."""

def T(en, es, ar, zh):
    return {"en": en, "es": es, "ar": ar, "zh": zh}

def _P(**k): return k

# ================================================================ PILLARS (merged into F2.PILLARS)
PILLARS = {

 # ---------------------------------------------------------------- Project Structuring & Development
 "developments/project-structuring": {
  "intro": T("Projects are not developed by declarations — they are developed by structure.",
             "Los proyectos no se desarrollan con declaraciones — se desarrollan con estructura.",
             "المشاريع لا تُطوَّر بالتصريحات — بل بالبنية.",
             "项目不是靠宣言开发的——而是靠架构。"),
  "intro_sub": T("From origination to operation or exit: twelve steps, one responsible structure, and a role defined by the mandate.",
                 "De la originación a la operación o salida: doce pasos, una sola estructura responsable y un rol definido por el mandato.",
                 "من النشأة إلى التشغيل أو التخارج: اثنتا عشرة خطوة، وبنية مسؤولة واحدة، ودور يحدّده التفويض.",
                 "从发起到运营或退出：十二个步骤、一个负责的架构、一个由授权界定的角色。"),
  "01": _P(p=[T(
    "XARU HOME structures development projects end to end — from origination and title verification to structuring, capital, execution and operation. Depending on the project, the jurisdiction, feasibility and the mandate, XARU may act as adviser, structurer, integrator, sponsor, development manager or strategic participant. XARU never claims a single role for every project: the role follows the mandate.",
    "XARU HOME estructura proyectos de desarrollo de principio a fin — desde la originación y la validación de titularidad hasta la estructuración, el capital, la ejecución y la operación. Dependiendo del proyecto, la jurisdicción, la viabilidad y el mandato, XARU puede actuar como asesor, estructurador, integrador, sponsor, gestor de desarrollo o participante estratégico. XARU nunca reclama un único rol para todos los proyectos: el rol sigue al mandato.",
    "تُهيكل XARU HOME مشاريع التطوير من البداية إلى النهاية — من النشأة والتحقّق من الملكية إلى الهيكلة ورأس المال والتنفيذ والتشغيل. بحسب المشروع والولاية القضائية والجدوى والتفويض، قد تعمل XARU كمستشار أو مُهيكل أو مُدمج أو راعٍ أو مدير تطوير أو مشارك استراتيجي. لا تدّعي XARU دوراً واحداً لكل المشاريع: الدور يتبع التفويض.",
    "XARU HOME 对开发项目进行端到端的架构——从项目发起与产权核验，到架构、资本、执行与运营。视项目、司法管辖区、可行性与授权而定，XARU 可担任顾问、架构方、整合方、发起方、开发管理方或战略参与方。XARU 从不宣称对所有项目扮演同一角色：角色取决于授权。")]),
  "02": _P(p=[T("Those who hold territory, capital or a project — and need the structure between them.",
                "Quienes tienen territorio, capital o un proyecto — y necesitan la estructura entre ellos.",
                "من يملكون أرضاً أو رأس مال أو مشروعاً — ويحتاجون البنية التي تجمعها.",
                "持有土地、资本或项目——并需要将三者连接之架构的各方。")],
           list=[T("Landowners with territory but no structure or partner", "Propietarios de suelo con territorio pero sin estructura ni socio", "ملّاك أراضٍ لديهم أرض دون بنية أو شريك", "拥有土地但缺乏架构或伙伴的地主"),
                 T("Developers requiring structuring, permits or capital", "Desarrolladores que requieren estructuración, permisos o capital", "مطوّرون يحتاجون إلى هيكلة أو تصاريح أو رأس مال", "需要架构、许可或资本的开发商"),
                 T("Investors and family offices entering development", "Inversionistas y family offices que entran en desarrollo", "مستثمرون ومكاتب عائلية يدخلون مجال التطوير", "进入开发领域的投资者与家族办公室"),
                 T("Communities and titleholders seeking an ordered process", "Comunidades y titulares que buscan un proceso ordenado", "مجتمعات وأصحاب حقوق يبحثون عن مسار منظّم", "寻求有序流程的社区与权利人"),
                 T("Sponsors of halted or incomplete projects", "Sponsors de proyectos detenidos o incompletos", "رعاة مشاريع متوقفة أو غير مكتملة", "停滞或未完工项目的发起方")]),
  "03": _P(p=[T("The structuring disciplines XARU brings to a project.", "Las disciplinas de estructuración que XARU aporta a un proyecto.", "تخصّصات الهيكلة التي تقدّمها XARU للمشروع.", "XARU 为项目提供的架构专业能力。")],
           list=[T("Feasibility and pre-feasibility", "Viabilidad y prefactibilidad", "الجدوى والجدوى الأولية", "可行性与预可行性"),
                 T("Legal and fiduciary structuring — including trust (fideicomiso) models", "Estructuración jurídica y fiduciaria — incluidos modelos de fideicomiso", "الهيكلة القانونية والائتمانية — بما فيها نماذج الائتمان العقاري", "法律与信托架构——包括信托（fideicomiso）模式"),
                 T("Vehicles and SPVs", "Vehículos y SPV", "الكيانات وشركات الغرض الخاص", "载体与特殊目的公司"),
                 T("Master plan and business model", "Master plan y modelo de negocio", "المخطط العام ونموذج العمل", "总体规划与商业模式"),
                 T("Licensing and permits", "Licencias y permisos", "التراخيص والتصاريح", "牌照与许可"),
                 T("Operator selection", "Selección de operador", "اختيار المشغّل", "运营商遴选"),
                 T("Development management", "Gestión de desarrollo", "إدارة التطوير", "开发管理"),
                 T("Commercialization and distribution", "Comercialización y distribución", "التسويق التجاري والتوزيع", "商业化与分销")]),
  "04": _P(p=[T("XARU intermediates, advises, structures, integrates, manages, co-develops or participates — the combination is defined case by case, in writing, before work begins. A distinguishing capability is fiduciary structuring: where the jurisdiction provides for it, land and project interests can be held in trust (fideicomiso), separating ownership, governance and economics so that every party is protected while the project takes form.",
                "XARU intermedia, asesora, estructura, integra, gestiona, codesarrolla o participa — la combinación se define caso por caso, por escrito, antes de comenzar. Una capacidad distintiva es la estructuración fiduciaria: donde la jurisdicción lo permite, el suelo y los intereses del proyecto pueden mantenerse en fideicomiso, separando propiedad, gobernanza y economía para que cada parte quede protegida mientras el proyecto toma forma.",
                "تتوسّط XARU وتستشير وتُهيكل وتُدمج وتدير وتشارك في التطوير أو تساهم — ويُحدَّد المزيج حالةً بحالة، كتابةً، قبل بدء العمل. ومن قدراتها المميّزة الهيكلة الائتمانية: حيث تتيح الولاية القضائية ذلك، يمكن حفظ الأرض وحقوق المشروع في ائتمان عقاري يفصل الملكية عن الحوكمة والاقتصاد، فتُحمى كل الأطراف بينما يتشكّل المشروع.",
                "XARU 可进行中介、咨询、架构、整合、管理、联合开发或参与——具体组合逐案确定，并在工作开始前以书面明确。其独到能力之一是信托架构：在司法管辖区允许的情况下，土地与项目权益可置于信托（fideicomiso）之中，将所有权、治理与经济利益分离，使各方在项目成形期间均获保护。")]),
  "05": _P(p=[T("What XARU does not do.", "Qué NO hace XARU.", "ما لا تقوم به XARU.", "XARU 不做的事。")],
           list=[T("Claim that it always develops — the role follows the mandate", "Afirmar que siempre desarrolla — el rol sigue al mandato", "الادعاء بأنها تطوّر دائماً — فالدور يتبع التفويض", "宣称自己总是开发方——角色取决于授权"),
                 T("Open economic negotiation before counterparty and title are clear", "Abrir la negociación económica antes de que contraparte y titularidad estén claras", "فتح التفاوض الاقتصادي قبل وضوح الطرف المقابل والملكية", "在对手方与产权明确之前开启经济谈判"),
                 T("Publish confidential structures, counterparties or terms", "Publicar estructuras, contrapartes o términos confidenciales", "نشر هياكل أو أطراف أو شروط سرّية", "公开保密的架构、对手方或条款"),
                 T("Make regulatory claims not backed by authorised entities", "Hacer afirmaciones regulatorias no respaldadas por entidades autorizadas", "تقديم ادعاءات تنظيمية لا تدعمها كيانات مرخّصة", "作出未经获授权实体支持的监管主张")]),
  "06": _P(p=[T("Twelve steps, visible from the first conversation. Not every project runs all twelve — but every project knows where it stands.",
                "Doce pasos, visibles desde la primera conversación. No todos los proyectos recorren los doce — pero todo proyecto sabe en qué punto está.",
                "اثنتا عشرة خطوة، مرئية منذ المحادثة الأولى. لا تمرّ كل المشاريع بالخطوات الاثنتي عشرة — لكن كل مشروع يعرف موقعه.",
                "十二个步骤，自首次对话起清晰可见。并非每个项目都走完十二步——但每个项目都清楚自己所处的位置。")],
           steps=[T("Origination", "Originación", "النشأة", "项目发起"),
                  T("Title and counterparty validation", "Validación de titularidad y contraparte", "التحقّق من الملكية والطرف المقابل", "产权与对手方核验"),
                  T("Pre-feasibility", "Prefactibilidad", "الجدوى الأولية", "预可行性"),
                  T("Due diligence", "Due diligence", "العناية الواجبة", "尽职调查"),
                  T("Legal and fiduciary structuring", "Estructuración jurídica y fiduciaria", "الهيكلة القانونية والائتمانية", "法律与信托架构"),
                  T("Financial model", "Modelo financiero", "النموذج المالي", "财务模型"),
                  T("Master plan", "Master plan", "المخطط العام", "总体规划"),
                  T("Capital and partners", "Capital y socios", "رأس المال والشركاء", "资本与合作伙伴"),
                  T("Permits and operators", "Permisos y operadores", "التصاريح والمشغّلون", "许可与运营商"),
                  T("Execution", "Ejecución", "التنفيذ", "执行"),
                  T("Commercialization", "Comercialización", "التسويق التجاري", "商业化"),
                  T("Operation or exit", "Operación o salida", "التشغيل أو التخارج", "运营或退出")]),
  "07": _P(p=[T("Structuring only works between aligned parties. Admission protects the project as much as the counterparties.",
                "La estructuración solo funciona entre partes alineadas. La admisión protege al proyecto tanto como a las contrapartes.",
                "لا تنجح الهيكلة إلا بين أطراف متوائمة. القبول يحمي المشروع كما يحمي الأطراف.",
                "架构只在目标一致的各方之间才能奏效。准入既保护项目，也保护对手方。")],
           list=[T("Verifiable title, or a credible and documented path to it", "Titularidad verificable, o una vía creíble y documentada hacia ella", "ملكية قابلة للتحقّق أو مسار موثّق وموثوق إليها", "可核验的产权，或可信且有据可查的取得路径"),
                 T("An identifiable, verifiable counterparty", "Una contraparte identificable y verificable", "طرف مقابل يمكن تحديده والتحقّق منه", "可识别、可核实的对手方"),
                 T("Scale and feasibility that justify a structured process", "Escala y viabilidad que justifiquen un proceso estructurado", "حجم وجدوى يبرّران مساراً منظّماً", "足以支撑结构化流程的规模与可行性"),
                 T("Acceptance of governance, confidentiality and sequence", "Aceptación de gobernanza, confidencialidad y secuencia", "قبول الحوكمة والسرّية والتسلسل", "接受治理、保密与流程顺序")]),
  "08": _P(p=[T("The working method was proven on ASHIMA and governs every structuring mandate: the counterparty is validated first; the legal structure is designed next; the community and titleholders are engaged; and only once minimum clarity exists does economic negotiation begin — formalised through letters of intent, memoranda of understanding or option instruments. Confidential detail never leaves the Deal Room.",
                "El método de trabajo se probó en ASHIMA y gobierna cada mandato de estructuración: primero se valida la contraparte; después se diseña la estructura legal; se incorpora a la comunidad y a los titulares; y solo cuando existe una claridad mínima comienza la negociación económica — formalizada mediante cartas de intención, memorandos de entendimiento o instrumentos de opción. El detalle confidencial nunca sale del Deal Room.",
                "أُثبتت منهجية العمل في ASHIMA وهي تحكم كل تفويض هيكلة: يُتحقّق أولاً من الطرف المقابل؛ ثم تُصمَّم البنية القانونية؛ ويُشرَك المجتمع وأصحاب الحقوق؛ ولا يبدأ التفاوض الاقتصادي إلا بعد حدٍّ أدنى من الوضوح — مُوثَّقاً بخطابات نوايا أو مذكرات تفاهم أو صكوك خيار. التفاصيل السرّية لا تغادر غرفة الصفقات أبداً.",
                "这一工作方法在 ASHIMA 项目上得到验证，并适用于每一项架构授权：先核实对手方；再设计法律结构；继而与社区及权利人沟通；只有在达到最低限度的明确性之后，才开始经济谈判——以意向书、谅解备忘录或期权文件的形式落实。保密细节绝不离开交易室。")],
           list=[T("In-house structuring and development management", "Estructuración y gestión de desarrollo propias", "هيكلة وإدارة تطوير داخلية", "自有架构与开发管理"),
                 T("Fiduciary structures with authorised entities where the activity requires it", "Estructuras fiduciarias con entidades autorizadas cuando la actividad lo requiere", "هياكل ائتمانية مع كيانات مرخّصة عندما يستلزم النشاط ذلك", "在业务需要时与获授权实体搭建信托结构"),
                 T("Legal, tax, planning and environmental partners by jurisdiction", "Partners legales, fiscales, urbanísticos y ambientales por jurisdicción", "شركاء قانونيون وضريبيون وتخطيطيون وبيئيون بحسب الولاية القضائية", "按司法管辖区配置的法律、税务、规划与环境合作伙伴"),
                 T("Capital, operator and joint-venture network", "Red de capital, operadores y joint ventures", "شبكة رأس مال ومشغّلين ومشاريع مشتركة", "资本、运营商与合资网络")]),
  "09": _P(p=[T("A landowner presents a coastal territory with fragmented title. XARU validates each titleholder, designs a trust to hold the land, engages the community, sequences the master plan, and brings a developer and capital into the structure — economic terms negotiated only after the structure is clear, and executed through option instruments. The territory moves from fragmentation to a development-ready position.",
                "Un propietario presenta un territorio costero con titularidad fragmentada. XARU valida a cada titular, diseña un fideicomiso para mantener el suelo, incorpora a la comunidad, secuencia el master plan e integra a un desarrollador y capital en la estructura — con términos económicos negociados solo cuando la estructura está clara, y ejecutados mediante instrumentos de opción. El territorio pasa de la fragmentación a una posición lista para el desarrollo.",
                "يعرض مالك أرضاً ساحلية بملكية مجزّأة. تتحقّق XARU من كل صاحب حق، وتصمّم ائتماناً عقارياً لحفظ الأرض، وتُشرك المجتمع، وترتّب المخطط العام على مراحل، وتُدخل مطوّراً ورأس مال في البنية — ولا تُتفاوَض الشروط الاقتصادية إلا بعد وضوح البنية، وتُنفَّذ عبر صكوك خيار. تنتقل الأرض من التجزئة إلى وضع جاهز للتطوير.",
                "一位业主提交了一片产权分散的滨海土地。XARU 逐一核实权利人，设计信托以持有土地，与社区沟通，分期编排总体规划，并将开发商与资本纳入该结构——经济条款仅在结构明确后谈判，并通过期权文件执行。这片土地由权属分散走向开发就绪。")]),
  "10": _P(p=[T("Every structuring mandate is governed by confidentiality, verified titles, documented sequence and a defined scope. Nothing is represented as permitted, held or agreed unless it has been verified under the mandate.",
                "Cada mandato de estructuración se rige por confidencialidad, títulos verificados, secuencia documentada y un alcance definido. Nada se presenta como permitido, en tenencia o acordado si no ha sido verificado bajo el mandato.",
                "يخضع كل تفويض هيكلة للسرّية والملكيات الموثّقة والتسلسل المُوثَّق ونطاق محدّد. لا يُعرَض شيء على أنه مرخّص أو محاز أو متّفق عليه ما لم يُتحقّق منه بموجب التفويض.",
                "每项架构授权均受保密、经核实的产权、有据可查的流程顺序与既定范围约束。凡未经授权核实之事项，一律不以已许可、已持有或已议定的名义呈现。")]),
  "11": _P(faq=[
    (T("Does XARU always develop the projects it structures?", "¿XARU siempre desarrolla los proyectos que estructura?", "هل تطوّر XARU دائماً المشاريع التي تُهيكلها؟", "XARU 总是亲自开发其架构的项目吗？"),
     T("No. Depending on the project, the jurisdiction, feasibility and the mandate, XARU may act as adviser, structurer, integrator, sponsor, development manager or strategic participant.",
       "No. Dependiendo del proyecto, la jurisdicción, la viabilidad y el mandato, XARU puede actuar como asesor, estructurador, integrador, sponsor, gestor de desarrollo o participante estratégico.",
       "لا. بحسب المشروع والولاية القضائية والجدوى والتفويض، قد تعمل XARU كمستشار أو مُهيكل أو مُدمج أو راعٍ أو مدير تطوير أو مشارك استراتيجي.",
       "不。视项目、司法管辖区、可行性与授权而定，XARU 可担任顾问、架构方、整合方、发起方、开发管理方或战略参与方。")),
    (T("Can land be held in trust while the project is structured?", "¿El suelo puede mantenerse en fideicomiso mientras se estructura el proyecto?", "هل يمكن حفظ الأرض في ائتمان أثناء هيكلة المشروع؟", "项目架构期间，土地可以置于信托之中吗？"),
     T("Where the jurisdiction provides for it, yes — fiduciary structures separate ownership, governance and economics, protecting every party during structuring.",
       "Donde la jurisdicción lo permite, sí — las estructuras fiduciarias separan propiedad, gobernanza y economía, protegiendo a cada parte durante la estructuración.",
       "حيث تتيح الولاية القضائية ذلك، نعم — تفصل الهياكل الائتمانية الملكية عن الحوكمة والاقتصاد، فتحمي كل الأطراف أثناء الهيكلة.",
       "在司法管辖区允许的情况下可以——信托结构将所有权、治理与经济利益分离，在架构期间保护各方。")),
    (T("When does price negotiation begin?", "¿Cuándo comienza la negociación de precio?", "متى يبدأ التفاوض على السعر؟", "价格谈判何时开始？"),
     T("Only once counterparty, title and structure have reached minimum clarity — then formalised through LOI, MOU or option instruments.",
       "Solo cuando contraparte, titularidad y estructura han alcanzado una claridad mínima — y entonces se formaliza mediante LOI, MOU o instrumentos de opción.",
       "فقط بعد أن يبلغ الطرف المقابل والملكية والبنية حداً أدنى من الوضوح — ثم يُوثَّق عبر خطاب نوايا أو مذكرة تفاهم أو صك خيار.",
       "只有当对手方、产权与结构达到最低限度的明确性之后——继而以 LOI、MOU 或期权文件落实。")),
   ]),
 },

 # ---------------------------------------------------------------- Capital & Strategic Partnerships
 "capital/strategic-partnerships": {
  "intro": T("Capital and projects, matched with discipline — never by introduction alone.",
             "Capital y proyectos, unidos con disciplina — nunca por una simple presentación.",
             "رأس المال والمشاريع، مقرونان بانضباط — لا بمجرّد تعارف.",
             "资本与项目，审慎对接——绝非仅凭引荐。"),
  "intro_sub": T("An explicit two-way structure, governed by a fourteen-stage process of verification, review and managed negotiation.",
                 "Una estructura explícita de doble vía, gobernada por un proceso de catorce etapas de verificación, revisión y negociación gestionada.",
                 "بنية ثنائية الاتجاه صريحة، يحكمها مسار من أربع عشرة مرحلة من التحقّق والمراجعة والتفاوض المُدار.",
                 "一套明确的双向架构，由核实、审查与受管理谈判构成的十四阶段流程治理。"),
  "01": _P(p=[T(
    "XARU HOME connects capital and projects as a principal, under its own diligence. XARU is not a simple matchmaker: every mandate passes through structured intake, verification, legal and tax review and managed negotiation before any two parties meet. The depth is in the process — not in a promise that capital will always be found.",
    "XARU HOME conecta capital y proyectos como principal, bajo su propia diligencia. XARU no es un simple matchmaker: cada mandato pasa por un intake estructurado, verificación, revisión legal y fiscal y una negociación gestionada antes de que dos partes se encuentren. La profundidad está en el proceso — no en la promesa de que siempre se encontrará capital.",
    "تربط XARU HOME رأس المال بالمشاريع كطرف أصيل، وفق عنايتها الخاصة. ليست XARU وسيطاً بسيطاً: يمرّ كل تفويض باستقبال منظّم وتحقّق ومراجعة قانونية وضريبية وتفاوض مُدار قبل أن يلتقي أي طرفين. العمق في المسار — لا في وعدٍ بأن رأس المال سيُوجَد دائماً.",
    "XARU HOME 以本人身份、依自身尽调连接资本与项目。XARU 并非简单的撮合者：每项委托都要经过结构化登记、核实、法律与税务审查以及受管理的谈判，双方才会见面。深度在于流程——而非承诺总能找到资本。")]),
  "02": _P(p=[T("Both sides of the table, held to the same standard of verification.",
                "Ambos lados de la mesa, sujetos al mismo estándar de verificación.",
                "جانبا الطاولة كلاهما، وفق معيار التحقّق نفسه.",
                "交易的两端，适用同一核实标准。")],
           list=[T("Owners and sponsors of assets and projects", "Propietarios y sponsors de activos y proyectos", "ملّاك ورعاة أصول ومشاريع", "资产与项目的业主及发起方"),
                 T("Funds, family offices and private investors", "Fondos, family offices e inversionistas privados", "صناديق ومكاتب عائلية ومستثمرون خاصّون", "基金、家族办公室与私人投资者"),
                 T("Developers and operators seeking positions", "Desarrolladores y operadores que buscan posiciones", "مطوّرون ومشغّلون يبحثون عن مراكز", "寻求头寸的开发商与运营商"),
                 T("Institutions with private mandates", "Instituciones con mandatos privados", "مؤسسات ذات تفويضات خاصة", "持有私人委托的机构")]),
  "03": _P(p=[T("An explicit two-way structure. Tell us which side of the table you are on.",
                "Una estructura explícita de doble vía. Indíquenos en qué lado de la mesa se encuentra.",
                "بنية ثنائية الاتجاه صريحة. أخبرنا في أي جانب من الطاولة أنت.",
                "明确的双向架构。请告知您位于交易的哪一端。")],
           cols=[
             {"h": T("Side A — I have an asset or a project, and I need:",
                     "Lado A — Tengo un activo o un proyecto, y necesito:",
                     "الجانب أ — لديّ أصل أو مشروع، وأحتاج إلى:",
                     "A 端——我有资产或项目，需要："),
              "cta": T("Present a project", "Presentar un proyecto", "قدّم مشروعاً", "提交项目"),
              "href": "opportunities/submit/#side-a",
              "items": [T("Capital", "Capital", "رأس مال", "资本"),
                        T("A developer", "Un desarrollador", "مطوّراً", "开发商"),
                        T("An operator", "Un operador", "مشغّلاً", "运营商"),
                        T("A buyer", "Un comprador", "مشترياً", "买家"),
                        T("A partner", "Un socio", "شريكاً", "合作伙伴"),
                        T("Distribution", "Distribución", "توزيعاً", "分销渠道"),
                        T("Restructuring", "Reestructuración", "إعادة هيكلة", "重组")]},
             {"h": T("Side B — I have capital or capability, and I am seeking:",
                     "Lado B — Tengo capital o capacidad, y busco:",
                     "الجانب ب — لديّ رأس مال أو قدرة، وأبحث عن:",
                     "B 端——我有资本或能力，正在寻求："),
              "cta": T("Deploy capital", "Desplegar capital", "استثمر رأس المال", "配置资本"),
              "href": "opportunities/submit/#side-b",
              "items": [T("Projects", "Proyectos", "مشاريع", "项目"),
                        T("Land", "Suelo", "أراضٍ", "土地"),
                        T("Operating assets", "Activos operativos", "أصولاً تشغيلية", "运营资产"),
                        T("Distressed opportunities", "Oportunidades distressed", "فرصاً متعثّرة", "困境资产机会"),
                        T("Joint ventures", "Joint ventures", "مشاريع مشتركة", "合资企业"),
                        T("Hotel developments", "Desarrollos hoteleros", "تطويرات فندقية", "酒店开发项目"),
                        T("Private mandates", "Mandatos privados", "تفويضات خاصة", "私人委托")]}]),
  "04": _P(p=[T("XARU does not simply introduce parties. It verifies both sides, protects information under NDA, opens a controlled data room, coordinates legal, tax and financial review, and manages the negotiation to closing — with a responsibility matrix that states who does what, at every stage.",
                "XARU no se limita a presentar a las partes. Verifica a ambos lados, protege la información bajo NDA, abre un data room controlado, coordina la revisión legal, fiscal y financiera, y gestiona la negociación hasta el cierre — con una matriz de responsabilidades que establece quién hace qué, en cada etapa.",
                "لا تكتفي XARU بتعريف الأطراف ببعضها. بل تتحقّق من الجانبين، وتحمي المعلومات بموجب اتفاقية سرية، وتفتح غرفة بيانات مضبوطة، وتنسّق المراجعة القانونية والضريبية والمالية، وتدير التفاوض حتى الإغلاق — بمصفوفة مسؤوليات تحدّد من يفعل ماذا في كل مرحلة.",
                "XARU 不只是引荐双方。它核实两端、以保密协议保护信息、开放受控数据室、协调法律、税务与财务审查，并管理谈判直至成交——辅以一份职责矩阵，明确每个阶段谁负责什么。")]),
  "05": _P(p=[T("What XARU does not do.", "Qué NO hace XARU.", "ما لا تقوم به XARU.", "XARU 不做的事。")],
           list=[T("Operate as a listing board or a simple matchmaker", "Operar como un tablón de anuncios o un simple matchmaker", "العمل كلوحة إعلانات أو وسيط بسيط", "充当信息板或简单撮合者"),
                 T("Promise that capital will always be secured", "Prometer que siempre se conseguirá capital", "الوعد بتأمين رأس المال دائماً", "承诺总能筹到资本"),
                 T("Circulate teasers or data without a mandate and an NDA", "Circular teasers o datos sin mandato y sin NDA", "تداول موجزات أو بيانات دون تفويض واتفاقية سرية", "在无委托与保密协议的情况下散发资料"),
                 T("Seat an unverified party at the table", "Sentar a la mesa a una parte no verificada", "إجلاس طرف غير موثّق إلى الطاولة", "让未经核实的一方上桌"),
                 T("Guarantee returns", "Garantizar rendimientos", "ضمان العوائد", "保证回报")]),
  "06": _P(p=[T("Fourteen stages, from first contact to follow-through. Not every transaction requires all fourteen — but every party knows which stage it is in.",
                "Catorce etapas, del primer contacto al seguimiento. No toda transacción requiere las catorce — pero cada parte sabe en qué etapa se encuentra.",
                "أربع عشرة مرحلة، من أول اتصال إلى المتابعة. لا تتطلّب كل صفقة المراحل الأربع عشرة — لكن كل طرف يعرف في أي مرحلة هو.",
                "十四个阶段，从初次接触到后续跟进。并非每笔交易都需要全部十四步——但每一方都清楚自己所处的阶段。")],
           steps=[T("Structured intake", "Intake estructurado", "استقبال منظّم", "结构化登记"),
                  T("Verification of the parties", "Verificación de las partes", "التحقّق من الأطراف", "各方核实"),
                  T("NDA", "NDA", "اتفاقية سرية", "保密协议"),
                  T("KYC / AML where applicable", "KYC / AML cuando corresponda", "اعرف عميلك / مكافحة غسل الأموال عند الاقتضاء", "适用时进行 KYC / AML"),
                  T("Preliminary review", "Revisión preliminar", "مراجعة أولية", "初步审查"),
                  T("Data room", "Data room", "غرفة البيانات", "数据室"),
                  T("Legal review", "Evaluación legal", "المراجعة القانونية", "法律评估"),
                  T("Tax review", "Evaluación fiscal", "المراجعة الضريبية", "税务评估"),
                  T("Financial analysis", "Análisis financiero", "التحليل المالي", "财务分析"),
                  T("Meeting coordination", "Coordinación de reuniones", "تنسيق الاجتماعات", "会议协调"),
                  T("Responsibility matrix", "Matriz de responsabilidades", "مصفوفة المسؤوليات", "职责矩阵"),
                  T("Negotiation", "Negociación", "التفاوض", "谈判"),
                  T("Closing", "Cierre", "الإغلاق", "成交"),
                  T("Follow-through", "Seguimiento", "المتابعة", "后续跟进")]),
  "07": _P(p=[T("A curated table. Admission protects both sides equally.",
                "Una mesa seleccionada. La admisión protege a ambos lados por igual.",
                "طاولة منتقاة. القبول يحمي الجانبين بالتساوي.",
                "一张经过甄选的谈判桌。准入同等保护双方。")],
           list=[T("Side A — verifiable ownership, sponsorship or mandate over the asset or project", "Lado A — titularidad, patrocinio o mandato verificables sobre el activo o proyecto", "الجانب أ — ملكية أو رعاية أو تفويض قابل للتحقّق على الأصل أو المشروع", "A 端——对资产或项目具有可核验的所有权、发起权或委托"),
                 T("Side B — verifiable capital or operating capability", "Lado B — capital o capacidad operativa verificables", "الجانب ب — رأس مال أو قدرة تشغيلية قابلة للتحقّق", "B 端——可核验的资本或运营能力"),
                 T("Realistic expectations on pricing, sequence and time", "Expectativas realistas de precio, secuencia y tiempo", "توقعات واقعية للسعر والتسلسل والوقت", "对价格、流程与时间的合理预期"),
                 T("Willingness to sign NDA and complete KYC where applicable", "Disposición a firmar NDA y completar KYC cuando corresponda", "الاستعداد لتوقيع اتفاقية سرية واستكمال اعرف عميلك عند الاقتضاء", "愿意签署保密协议并在适用时完成 KYC")]),
  "08": _P(p=[T("Transaction discipline in-house; specialist review through authorised entities and partners where the activity requires it.",
                "Disciplina transaccional propia; revisión especializada a través de entidades y partners autorizados cuando la actividad lo requiere.",
                "انضباط صفقات داخلي؛ ومراجعة متخصّصة عبر كيانات وشركاء مرخّصين عندما يستلزم النشاط ذلك.",
                "自有交易纪律；在业务需要时通过获授权实体与合作伙伴进行专业审查。")],
           list=[T("In-house due diligence, deal origination and transaction management", "Due diligence, originación y gestión de transacciones propias", "عناية واجبة ونشأة صفقات وإدارة معاملات داخلية", "自有尽调、交易发起与交易管理"),
                 T("Legal and tax coordination by jurisdiction", "Coordinación legal y fiscal por jurisdicción", "تنسيق قانوني وضريبي بحسب الولاية القضائية", "按司法管辖区进行法律与税务协调"),
                 T("KYC / AML through regulated channels where applicable", "KYC / AML por canales regulados cuando corresponda", "اعرف عميلك / مكافحة الغسل عبر قنوات منظّمة عند الاقتضاء", "适用时通过受监管渠道进行 KYC / AML"),
                 T("An international network of funds, family offices, developers and operators", "Una red internacional de fondos, family offices, desarrolladores y operadores", "شبكة دولية من الصناديق والمكاتب العائلية والمطوّرين والمشغّلين", "由基金、家族办公室、开发商与运营商组成的国际网络")]),
  "09": _P(p=[T("An owner presents a halted resort seeking recapitalisation — Side A. A family office holds a private mandate to enter hospitality — Side B. XARU verifies both parties, executes NDAs, opens the data room, coordinates legal, tax and financial review, sets the responsibility matrix and manages negotiation to closing. Neither party met the other until both had been verified.",
                "Un propietario presenta un resort detenido que busca recapitalización — Lado A. Un family office tiene un mandato privado para entrar en hostelería — Lado B. XARU verifica a ambas partes, ejecuta los NDA, abre el data room, coordina la revisión legal, fiscal y financiera, fija la matriz de responsabilidades y gestiona la negociación hasta el cierre. Ninguna parte conoció a la otra hasta que ambas fueron verificadas.",
                "يعرض مالك منتجعاً متوقفاً يبحث عن إعادة رسملة — الجانب أ. ويحمل مكتب عائلي تفويضاً خاصاً لدخول قطاع الضيافة — الجانب ب. تتحقّق XARU من الطرفين، وتُبرم اتفاقيات السرية، وتفتح غرفة البيانات، وتنسّق المراجعة القانونية والضريبية والمالية، وتضع مصفوفة المسؤوليات، وتدير التفاوض حتى الإغلاق. لم يلتقِ الطرفان حتى تُحُقِّق من كليهما.",
                "一位业主提交一处寻求再融资的停滞度假村——A 端。一家家族办公室持有进入酒店业的私人委托——B 端。XARU 核实双方、签署保密协议、开放数据室、协调法律、税务与财务审查、设定职责矩阵并管理谈判直至成交。在双方均通过核实之前，彼此从未见面。")]),
  "10": _P(p=[T("Introductions occur only between verified parties, under NDA, with KYC / AML completed through regulated channels where applicable. XARU does not promise capital — it governs the process that allows capital and projects to meet safely.",
                "Las presentaciones ocurren solo entre partes verificadas, bajo NDA, con KYC / AML completado por canales regulados cuando corresponda. XARU no promete capital — gobierna el proceso que permite que capital y proyectos se encuentren con seguridad.",
                "لا تتم التعريفات إلا بين أطراف موثّقة، بموجب اتفاقية سرية، مع استكمال اعرف عميلك / مكافحة الغسل عبر قنوات منظّمة عند الاقتضاء. لا تعد XARU برأس المال — بل تحكم المسار الذي يتيح لرأس المال والمشاريع أن يلتقيا بأمان.",
                "引荐仅在经核实的各方之间进行，受保密协议约束，并在适用时通过受监管渠道完成 KYC / AML。XARU 不承诺资本——它治理让资本与项目安全相遇的流程。")]),
  "11": _P(faq=[
    (T("Is XARU a broker of introductions?", "¿XARU es un bróker de presentaciones?", "هل XARU وسيط تعارف؟", "XARU 是引荐中介吗？"),
     T("No. Every mandate runs through verification, NDA, review and managed negotiation — introductions are one stage of a fourteen-stage process.",
       "No. Cada mandato pasa por verificación, NDA, revisión y negociación gestionada — las presentaciones son una etapa de un proceso de catorce.",
       "لا. يمرّ كل تفويض بالتحقّق واتفاقية السرية والمراجعة والتفاوض المُدار — والتعريف مرحلة واحدة من مسار من أربع عشرة مرحلة.",
       "不是。每项委托都要经过核实、保密协议、审查与受管理的谈判——引荐只是十四个阶段中的一步。")),
    (T("Does XARU guarantee that capital will be found?", "¿XARU garantiza que se encontrará capital?", "هل تضمن XARU إيجاد رأس المال؟", "XARU 保证能找到资本吗？"),
     T("No. XARU governs a disciplined process; outcomes depend on the asset, the market and the parties.",
       "No. XARU gobierna un proceso disciplinado; los resultados dependen del activo, del mercado y de las partes.",
       "لا. تحكم XARU مساراً منضبطاً؛ والنتائج تتوقف على الأصل والسوق والأطراف.",
       "不保证。XARU 治理一套有纪律的流程；结果取决于资产、市场与各方。")),
    (T("How is confidentiality preserved?", "¿Cómo se preserva la confidencialidad?", "كيف تُصان السرّية؟", "如何保障保密性？"),
     T("Public teasers only; identities, financials and sensitive terms are released solely inside the Private Deal Room, under NDA.",
       "Solo teasers públicos; identidades, datos financieros y términos sensibles se liberan únicamente dentro del Private Deal Room, bajo NDA.",
       "موجزات علنية فقط؛ ولا تُتاح الهويات والبيانات المالية والشروط الحسّاسة إلا داخل غرفة الصفقات الخاصة، بموجب اتفاقية سرية.",
       "公开的仅是简报；身份、财务与敏感条款只在私人交易室内、保密协议之下披露。")),
   ]),
 },
}

# ================================================================ Capital door page
CAPITAL_DOOR = {
 "lead": T("Capital and projects, matched with discipline. XARU HOME operates an explicit two-way structure: projects that seek capital, and capital that seeks projects — both held to the same standard of verification before they ever meet.",
           "Capital y proyectos, unidos con disciplina. XARU HOME opera una estructura explícita de doble vía: proyectos que buscan capital, y capital que busca proyectos — ambos sujetos al mismo estándar de verificación antes de encontrarse.",
           "رأس المال والمشاريع، مقرونان بانضباط. تُدير XARU HOME بنية ثنائية الاتجاه صريحة: مشاريع تبحث عن رأس مال، ورأس مال يبحث عن مشاريع — وكلاهما وفق معيار التحقّق نفسه قبل أن يلتقيا.",
           "资本与项目，审慎对接。XARU HOME 运作一套明确的双向架构：寻求资本的项目，与寻求项目的资本——双方在见面之前均须通过同一标准的核实。"),
 "not_matchmaker": T("XARU is not a simple matchmaker. The depth is in the process: intake, verification, NDA, KYC / AML where applicable, data room, legal, tax and financial review, and managed negotiation to closing.",
           "XARU no es un simple matchmaker. La profundidad está en el proceso: intake, verificación, NDA, KYC / AML cuando corresponda, data room, revisión legal, fiscal y financiera, y negociación gestionada hasta el cierre.",
           "ليست XARU وسيطاً بسيطاً. العمق في المسار: الاستقبال، والتحقّق، واتفاقية السرية، واعرف عميلك / مكافحة الغسل عند الاقتضاء، وغرفة البيانات، والمراجعة القانونية والضريبية والمالية، والتفاوض المُدار حتى الإغلاق.",
           "XARU 并非简单的撮合者。深度在于流程：登记、核实、保密协议、适用时的 KYC / AML、数据室、法律、税务与财务审查，以及受管理的谈判直至成交。"),
 "division_eyebrow": T("The division", "La división", "القسم", "板块"),
 "division_title": T("Capital & Strategic Partnerships", "Capital y Alianzas Estratégicas", "رأس المال والشراكات الاستراتيجية", "资本与战略合作"),
 "division_lead": T("The full pillar — who we serve, the fourteen-stage process, admission criteria, governance and FAQ.",
                    "El pilar completo — a quién servimos, el proceso de catorce etapas, criterios de admisión, gobernanza y preguntas frecuentes.",
                    "الركيزة الكاملة — لمن نعمل، ومسار المراحل الأربع عشرة، ومعايير القبول، والحوكمة، والأسئلة الشائعة.",
                    "完整支柱页——服务对象、十四阶段流程、准入标准、治理与常见问题。"),
 "division_cta": T("View the division", "Ver la división", "عرض القسم", "查看板块"),
 "dealroom_eyebrow": T("Private market", "Mercado privado", "السوق الخاص", "私人市场"),
 "dealroom_title": T("Private Deal Room", "Sala de Operaciones Privada", "غرفة الصفقات الخاصة", "私人交易室"),
 "dealroom_lead": T("Large and sensitive opportunities are shown as public teasers only. Identities, financials, licences and price travel a nine-step private route — access request, verification, NDA, approval, data room, adviser, transaction.",
                    "Las oportunidades grandes y sensibles se muestran solo como teasers públicos. Identidades, financieros, licencias y precio recorren una ruta privada de nueve pasos — solicitud de acceso, verificación, NDA, aprobación, data room, asesor, transacción.",
                    "تُعرض الفرص الكبيرة والحسّاسة كموجزات علنية فقط. أما الهويات والبيانات المالية والتراخيص والسعر فتسلك مساراً خاصاً من تسع خطوات — طلب الوصول، التحقّق، اتفاقية السرية، الموافقة، غرفة البيانات، المستشار، الصفقة.",
                    "大型及敏感机会仅以公开简报形式展示。身份、财务、牌照与价格须经九步私人路径——申请访问、核实、保密协议、批准、数据室、顾问、交易。"),
 "dealroom_cta": T("Enter the Deal Room", "Entrar a la Sala de Operaciones", "ادخل غرفة الصفقات", "进入交易室"),
}

# ================================================================ Private Deal Room page
DEALROOM = {
 "title": T("Private Deal Room", "Sala de Operaciones Privada", "غرفة الصفقات الخاصة", "私人交易室"),
 "eyebrow": T("Private market", "Mercado privado", "السوق الخاص", "私人市场"),
 "lead": T("Some opportunities are too large, too sensitive or too strategic for a public listing. The Private Deal Room lets them exist — visible enough to be real, protected enough to be safe.",
           "Algunas oportunidades son demasiado grandes, sensibles o estratégicas para un listado público. El Private Deal Room les permite existir — lo bastante visibles para ser reales, lo bastante protegidas para ser seguras.",
           "بعض الفرص أكبر وأكثر حساسية واستراتيجية من أن تُعرض علناً. تتيح لها غرفة الصفقات الخاصة أن تُوجَد — ظاهرة بما يكفي لتكون حقيقية، ومحمية بما يكفي لتكون آمنة.",
           "有些机会规模过大、过于敏感或过于关键，不宜公开挂牌。私人交易室让它们得以存在——足够可见以证明其真实，足够受保护以确保其安全。"),
 "sub": T("Every confidential opportunity travels the same nine-step route. No step is skipped; no information is released ahead of its step.",
          "Cada oportunidad confidencial recorre la misma ruta de nueve pasos. Ningún paso se omite; ninguna información se libera antes de su paso.",
          "تسلك كل فرصة سرّية المسار ذاته المؤلَّف من تسع خطوات. لا تُتجاوَز خطوة، ولا تُتاح معلومة قبل خطوتها.",
          "每个保密机会都走同一条九步路径。任何一步都不跳过；任何信息都不提前披露。"),
 "route_eyebrow": T("The private route", "La ruta privada", "المسار الخاص", "私人路径"),
 "route_title": T("Nine steps, in order", "Nueve pasos, en orden", "تسع خطوات، بالترتيب", "九个步骤，依序进行"),
 "steps": [
   (T("Public teaser", "Teaser público", "الموجز العلني", "公开简报"),
    T("The opportunity is announced without owners, coordinates, financials or price.",
      "La oportunidad se anuncia sin propietarios, coordenadas, financieros ni precio.",
      "تُعلَن الفرصة دون ملّاك أو إحداثيات أو بيانات مالية أو سعر.",
      "机会公布时不含业主、坐标、财务或价格。")),
   (T("Access request", "Solicitud de acceso", "طلب الوصول", "访问申请"),
    T("The interested party requests private access through the form below.",
      "La parte interesada solicita acceso privado mediante el formulario inferior.",
      "يطلب الطرف المهتم وصولاً خاصاً عبر النموذج أدناه.",
      "有意向方通过下方表单申请私人访问。")),
   (T("Identity and profile verification", "Verificación de identidad y perfil", "التحقّق من الهوية والملف", "身份与背景核实"),
    T("Who is asking, in what capacity, and with what capability.",
      "Quién pregunta, en qué calidad y con qué capacidad.",
      "من يسأل، وبأي صفة، وبأي قدرة.",
      "核实申请者是谁、以何种身份、具备何种能力。")),
   (T("NDA", "NDA", "اتفاقية السرية", "保密协议"),
    T("A non-disclosure agreement is executed before any sensitive detail moves.",
      "Se ejecuta un acuerdo de confidencialidad antes de que se mueva cualquier detalle sensible.",
      "تُبرَم اتفاقية عدم إفصاح قبل انتقال أي تفصيل حسّاس.",
      "在任何敏感细节流转之前，先签署保密协议。")),
   (T("KYC / AML where applicable", "KYC / AML cuando corresponda", "اعرف عميلك / مكافحة الغسل عند الاقتضاء", "适用时进行 KYC / AML"),
    T("Completed through regulated channels when the transaction requires it.",
      "Completado por canales regulados cuando la transacción lo requiere.",
      "يُستكمَل عبر قنوات منظّمة عندما تستلزم الصفقة ذلك.",
      "当交易需要时，通过受监管渠道完成。")),
   (T("Internal approval", "Aprobación interna", "الموافقة الداخلية", "内部批准"),
    T("XARU reviews the request against the mandate before opening anything.",
      "XARU revisa la solicitud contra el mandato antes de abrir nada.",
      "تراجع XARU الطلب وفق التفويض قبل فتح أي شيء.",
      "XARU 在开放任何内容之前，对照委托审核该申请。")),
   (T("Data room", "Data room", "غرفة البيانات", "数据室"),
    T("Documents, financials and licences are released inside a controlled environment.",
      "Documentos, financieros y licencias se liberan dentro de un entorno controlado.",
      "تُتاح المستندات والبيانات المالية والتراخيص داخل بيئة مضبوطة.",
      "文件、财务与牌照在受控环境内披露。")),
   (T("Adviser assignment", "Asignación de asesor", "تعيين مستشار", "指派顾问"),
    T("A dedicated adviser carries the party through the transaction.",
      "Un asesor dedicado acompaña a la parte durante la transacción.",
      "يرافق مستشار مخصّص الطرف خلال الصفقة.",
      "由专属顾问陪同该方完成交易。")),
   (T("Transaction process", "Proceso de transacción", "مسار الصفقة", "交易流程"),
    T("Negotiation, structure and closing, managed under one responsibility.",
      "Negociación, estructura y cierre, gestionados bajo una sola responsabilidad.",
      "التفاوض والهيكلة والإغلاق، تُدار تحت مسؤولية واحدة.",
      "谈判、架构与成交，在单一责任下管理。")),
 ],
 "protect_eyebrow": T("What is protected", "Qué se protege", "ما الذي يُحمى", "受保护的内容"),
 "protect_title": T("What never appears in public", "Lo que nunca aparece en público", "ما لا يظهر علناً أبداً", "绝不公开出现的信息"),
 "protect_items": [
   T("Owners' identities", "La identidad de los propietarios", "هويات الملّاك", "业主身份"),
   T("Coordinates and exact locations", "Coordenadas y ubicaciones exactas", "الإحداثيات والمواقع الدقيقة", "坐标与确切位置"),
   T("Financial statements", "Estados financieros", "البيانات المالية", "财务报表"),
   T("Licences and permits", "Licencias y permisos", "التراخيص والتصاريح", "牌照与许可"),
   T("Legal documents", "Documentos legales", "المستندات القانونية", "法律文件"),
   T("Sensitive price", "El precio sensible", "السعر الحسّاس", "敏感价格"),
   T("Strategic information", "La información estratégica", "المعلومات الاستراتيجية", "战略信息"),
 ],
 "teaser_eyebrow": T("Currently in the Deal Room", "Actualmente en la Sala de Operaciones", "حالياً في غرفة الصفقات", "目前在交易室中"),
 "teaser_title": T("Confidential opportunities", "Oportunidades confidenciales", "فرص سرّية", "保密机会"),
 "teaser_lead": T("Public teasers of opportunities currently under mandate. Everything beyond the teaser requires the nine-step route.",
                  "Teasers públicos de oportunidades actualmente bajo mandato. Todo lo que está más allá del teaser requiere la ruta de nueve pasos.",
                  "موجزات علنية لفرص قيد التفويض حالياً. كل ما يتجاوز الموجز يتطلّب مسار الخطوات التسع.",
                  "当前受托机会的公开简报。简报之外的一切均须经过九步路径。"),
 "form_eyebrow": T("Begin the route", "Iniciar la ruta", "ابدأ المسار", "开始路径"),
 "form_title": T("Request private access", "Solicitar acceso privado", "طلب وصول خاص", "申请私人访问"),
 "f_name": T("Full name", "Nombre completo", "الاسم الكامل", "全名"),
 "f_entity": T("Entity / family office", "Entidad / family office", "الكيان / المكتب العائلي", "实体 / 家族办公室"),
 "f_role": T("Role / capacity", "Rol / calidad en la que actúa", "الدور / الصفة", "角色 / 身份"),
 "f_jurisdiction": T("Jurisdiction", "Jurisdicción", "الولاية القضائية", "司法管辖区"),
 "f_interest": T("Area of interest", "Área de interés", "مجال الاهتمام", "关注领域"),
 "f_ref": T("Opportunity reference (optional)", "Referencia de oportunidad (opcional)", "مرجع الفرصة (اختياري)", "机会编号（可选）"),
 "f_message": T("Message", "Mensaje", "الرسالة", "留言"),
 "submit": T("Request access", "Solicitar acceso", "طلب الوصول", "申请访问"),
 "note": T("Requests are reviewed against the mandate. Backend integration is scheduled for Phase 6; no data is transmitted from this form.",
           "Las solicitudes se revisan contra el mandato. La integración de backend está prevista para la Fase 6; este formulario no transmite datos.",
           "تُراجَع الطلبات وفق التفويض. تكامل الخادم مقرّر للمرحلة 6؛ لا يُرسل هذا النموذج أي بيانات.",
           "申请将对照委托进行审核。后端集成计划于第六阶段完成；此表单不传输任何数据。"),
 "desk_eyebrow": T("Private Desk", "Mesa Privada", "المكتب الخاص", "私人服务台"),
 "desk_title": T("One conversation. One structure. Total confidentiality.",
                 "Una conversación. Una estructura. Total confidencialidad.",
                 "محادثة واحدة. بنية واحدة. سرّية تامّة.", "一次对话。单一架构。全然保密。"),
 "desk_cta": T("Speak with the Private Desk", "Hablar con la Mesa Privada", "تحدّث مع المكتب الخاص", "联系私人服务台"),
}

# ================================================================ Submit — two clear routes
SUBMIT2 = {
 "lead": T("XARU works as a principal on both sides of the table. Two routes, one standard of verification — tell us which side you are on.",
           "XARU actúa como principal en ambos lados de la mesa. Dos recorridos, un mismo estándar de verificación — indíquenos en qué lado se encuentra.",
           "تعمل XARU كطرف أصيل على جانبَي الطاولة. مساران ومعيار تحقّق واحد — أخبرنا في أي جانب أنت.",
           "XARU 以本人身份立于交易两端。两条路径、同一核实标准——请告知您位于哪一侧。"),
 "routeA_h": T("Route A — Submit a project", "Recorrido A — Presentar un proyecto", "المسار أ — تقديم مشروع", "路径 A——提交项目"),
 "routeA_sub": T("I have an asset or a project and I need capital, a developer, an operator, a buyer, a partner, distribution or restructuring.",
                 "Tengo un activo o un proyecto y necesito capital, un desarrollador, un operador, un comprador, un socio, distribución o reestructuración.",
                 "لديّ أصل أو مشروع وأحتاج إلى رأس مال أو مطوّر أو مشغّل أو مشترٍ أو شريك أو توزيع أو إعادة هيكلة.",
                 "我有资产或项目，需要资本、开发商、运营商、买家、合作伙伴、分销渠道或重组。"),
 "routeA_steps": [
   T("Describe the asset or project privately", "Describa el activo o proyecto de forma privada", "صف الأصل أو المشروع بسرّية", "私密描述资产或项目"),
   T("Preliminary review by the relevant division", "Revisión preliminar por la división correspondiente", "مراجعة أولية من القسم المختص", "由相关板块进行初步审查"),
   T("NDA where the information requires it", "NDA cuando la información lo requiera", "اتفاقية سرية عندما تستلزم المعلومات ذلك", "信息需要时签署保密协议"),
   T("Verification of title and counterparty", "Verificación de titularidad y contraparte", "التحقّق من الملكية والطرف المقابل", "核实产权与对手方"),
   T("A structured process begins — never a listing", "Comienza un proceso estructurado — nunca un simple listado", "يبدأ مسار منظّم — لا مجرّد إدراج", "启动结构化流程——绝非简单挂牌"),
 ],
 "routeB_h": T("Route B — Deploy capital", "Recorrido B — Desplegar capital", "المسار ب — استثمار رأس المال", "路径 B——配置资本"),
 "routeB_sub": T("I have capital or capability and I am seeking projects, land, operating assets, distressed opportunities, joint ventures, hotel developments or private mandates.",
                 "Tengo capital o capacidad y busco proyectos, suelo, activos operativos, oportunidades distressed, joint ventures, desarrollos hoteleros o mandatos privados.",
                 "لديّ رأس مال أو قدرة وأبحث عن مشاريع أو أراضٍ أو أصول تشغيلية أو فرص متعثّرة أو مشاريع مشتركة أو تطويرات فندقية أو تفويضات خاصة.",
                 "我有资本或能力，正在寻求项目、土地、运营资产、困境资产机会、合资、酒店开发或私人委托。"),
 "routeB_steps": [
   T("State your criteria and indicative ticket", "Indique sus criterios y ticket indicativo", "حدّد معاييرك وقيمتك الاسترشادية", "说明您的标准与指示性额度"),
   T("Preliminary review of fit against live mandates", "Revisión preliminar de encaje con los mandatos activos", "مراجعة أولية للملاءمة مع التفويضات النشطة", "对照在册委托初审匹配度"),
   T("NDA and KYC / AML where applicable", "NDA y KYC / AML cuando corresponda", "اتفاقية سرية واعرف عميلك / مكافحة الغسل عند الاقتضاء", "适用时签署保密协议并进行 KYC / AML"),
   T("Verification of capital or capability", "Verificación del capital o la capacidad", "التحقّق من رأس المال أو القدرة", "核实资本或能力"),
   T("Curated opportunities through the Private Deal Room", "Oportunidades seleccionadas a través del Private Deal Room", "فرص منتقاة عبر غرفة الصفقات الخاصة", "经私人交易室获得甄选机会"),
 ],
 "after_eyebrow": T("Expectations", "Expectativas", "التوقعات", "预期"),
 "after_title": T("What happens after you submit", "Qué pasa después de enviar", "ماذا يحدث بعد الإرسال", "提交之后会发生什么"),
 "after_steps": [
   T("Preliminary review — every submission is read by the relevant division", "Revisión preliminar — cada envío es leído por la división correspondiente", "مراجعة أولية — يقرأ القسم المختص كل طلب", "初步审查——每份提交均由相关板块阅读"),
   T("NDA, where the information you shared requires protection", "NDA, cuando la información compartida requiera protección", "اتفاقية سرية، عندما تحتاج المعلومات المشاركة إلى حماية", "保密协议——当您提供的信息需要保护时"),
   T("Verification of the party and the position", "Verificación de la parte y de la posición", "التحقّق من الطرف والمركز", "核实相关方与其头寸"),
   T("A reasoned response within business days — including when the answer is no", "Una respuesta razonada en días hábiles — incluso cuando la respuesta es no", "ردّ مُعلَّل في غضون أيام عمل — حتى عندما يكون الجواب لا", "在工作日内给出附理由的答复——即使答案是否定的"),
 ],
 "form_eyebrow": T("The intake", "El formulario", "نموذج الاستقبال", "登记表"),
 "form_title": T("Submit privately", "Enviar de forma privada", "الإرسال بسرّية", "保密提交"),
}

# ================================================================ Phase 6 — Developments door
# Real copy for the Developments door page (replaces the Phase 1 generic shell).
DEV_DOOR = {
 "lead": T("Land and master developments, from vision to delivery. XARU HOME works where territory, structuring and execution meet — acting as adviser, structurer, integrator, sponsor or co-developer, depending on the project, the jurisdiction, the feasibility and the mandate.",
           "Suelo y desarrollos maestros, de la visión a la entrega. XARU HOME trabaja donde se encuentran territorio, estructuración y ejecución — actuando como asesor, estructurador, integrador, sponsor o codesarrollador, según el proyecto, la jurisdicción, la viabilidad y el mandato.",
           "الأراضي والتطويرات الكبرى، من الرؤية إلى التسليم. تعمل XARU HOME حيث تلتقي الأرض والهيكلة والتنفيذ — بصفة مستشار أو مُهيكل أو مُدمج أو راعٍ أو مطوّر شريك، بحسب المشروع والولاية القضائية والجدوى والتفويض.",
           "土地与总体开发，从愿景到交付。XARU HOME 立于土地、架构与执行的交汇处——视项目、司法管辖区、可行性与授权而定，可担任顾问、架构方、整合方、发起方或联合开发者。"),
 "continuity": T("A development is not declared; it is structured. Title and territory first, then feasibility, vehicle, licensing, capital, operator and delivery — one responsibility across the whole chain, never a hand-off between strangers.",
                 "Un desarrollo no se declara; se estructura. Primero título y territorio, después viabilidad, vehículo, licencias, capital, operador y entrega — una sola responsabilidad en toda la cadena, nunca un traspaso entre desconocidos.",
                 "التطوير لا يُعلَن، بل يُهيكَل. الملكية والأرض أولاً، ثم الجدوى والكيان والتراخيص ورأس المال والمشغّل والتسليم — مسؤولية واحدة عبر السلسلة كاملة، لا تسليم بين غرباء.",
                 "开发不是宣布出来的，而是架构出来的。先是产权与土地，其后是可行性、载体、牌照、资本、运营商与交付——整条链条统一担责，绝非在陌生人之间层层转手。"),
 "land_eyebrow": T("Territory", "Territorio", "الأرض", "土地"),
 "land_title": T("Land & Master Developments", "Suelo y Desarrollos Maestros", "الأراضي والتطويرات الكبرى", "土地与总体开发"),
 "land_lead": T("Large land, coastal and resort land, permitted land and land in regularization, master plans, planned communities and signature destinations such as ASHIMA.",
                "Grandes extensiones, suelo costero y de resorts, suelo con permisos y en regularización, master plans, comunidades planificadas y destinos emblemáticos como ASHIMA.",
                "أراضٍ واسعة وساحلية وأراضي منتجعات وأراضٍ مرخّصة وأخرى قيد التسوية، ومخططات عامة ومجتمعات مخططة ووجهات مميّزة مثل ASHIMA.",
                "大宗土地、滨海与度假村用地、已获许可及权属规整中的土地，以及总体规划、规划社区与 ASHIMA 等标志性目的地。"),
 "struct_eyebrow": T("Execution", "Ejecución", "التنفيذ", "执行"),
 "struct_title": T("Project Structuring & Development", "Estructuración y Desarrollo de Proyectos", "هيكلة وتطوير المشاريع", "项目架构与开发"),
 "struct_lead": T("Feasibility, legal and fiduciary structuring, SPVs, master plan and business model, licensing, operator selection, development management and commercialization.",
                  "Viabilidad, estructuración jurídica y fiduciaria, SPV, master plan y modelo de negocio, licencias, selección de operador, gestión de desarrollo y comercialización.",
                  "الجدوى، والهيكلة القانونية والائتمانية، وكيانات SPV، والمخطط العام ونموذج العمل، والتراخيص، واختيار المشغّل، وإدارة التطوير والتسويق التجاري.",
                  "可行性、法律与信托架构、SPV 载体、总体规划与商业模式、牌照许可、运营商遴选、开发管理与商业化。"),
 "view_division": T("View the division", "Ver la división", "عرض القسم", "查看板块"),
 "chain_eyebrow": T("The chain", "La cadena", "السلسلة", "链条"),
 "chain_title": T("From land to legacy", "Del suelo al legado", "من الأرض إلى الإرث", "从土地到传承"),
 "chain_lead": T("Origination and title verification, feasibility and master plan, vehicle and licensing, capital and partners, construction and operator, commercialization and delivery. Each step is answered for by the same structure — and the projects that are already open sit in the land and opportunities catalogue.",
                 "Originación y verificación de título, viabilidad y master plan, vehículo y licencias, capital y socios, construcción y operador, comercialización y entrega. De cada paso responde la misma estructura — y los proyectos ya abiertos están en el catálogo de suelo y oportunidades.",
                 "النشأة والتحقّق من الملكية، والجدوى والمخطط العام، والكيان والتراخيص، ورأس المال والشركاء، والإنشاء والمشغّل، والتسويق والتسليم. عن كل خطوة تُسأل البنية نفسها — والمشاريع المفتوحة حالياً موجودة في كتالوج الأراضي والفرص.",
                 "寻源与产权核验、可行性与总体规划、载体与牌照、资本与伙伴、施工与运营商、商业化与交付。每一步都由同一架构负责——已开放的项目均列于土地与机会目录。"),
 "chain_link1": T("Land & opportunities catalogue", "Catálogo de suelo y oportunidades", "كتالوج الأراضي والفرص", "土地与机会目录"),
 "chain_link2": T("Capital & Transactions", "Capital y Transacciones", "رأس المال والصفقات", "资本与交易"),
}
