# -*- coding: utf-8 -*-
"""XARU HOME — Phase 4 copy (business infrastructure).
Real pillar copy for Trade & Financial Infrastructure and Corporate Services &
Relocation, plus the Business Infrastructure door page — all in EN/ES/AR/ZH.
Consumed by gen_i18n.py. Rules (DERROTERO §6/§7):
· Continuity narrative — Trade & Financial is the CONTINUATION of the operation,
  never a scattered side business.
· NEVER "we are a global financial institution". Permitted formulation only:
  "XARU designs, integrates and coordinates financial and technological
  infrastructure for international operations, working with authorised entities
  and providers where the activity requires it."
· Three layers always distinguished: technology developed by XARU or its
  companies / services provided directly / regulated services provided by
  authorised entities or partners. No internal platform names are ever
  published.
· Corporate Services is an establishment structure, not a visa agency. Two
  separate journeys: Corporate Landing and Private & Family Landing.
· "Coordinated with specialised legal counsel in each jurisdiction."
· Brand names never translated · sober patrimonial tone · [PHASE 0] marks
  pending data."""

def T(en, es, ar, zh):
    return {"en": en, "es": es, "ar": ar, "zh": zh}

def _P(**k): return k

# ================================================================ PILLARS (merged into F2.PILLARS)
PILLARS = {

 # ---------------------------------------------------------------- Trade & Financial Infrastructure
 "business-infrastructure/trade-financial": {
  "intro": T("When an asset does not end at the sale, the operation continues — and so does XARU.",
             "Cuando un activo no termina en la compraventa, la operación continúa — y XARU también.",
             "عندما لا ينتهي الأصل عند البيع والشراء، تستمرّ العملية — وتستمرّ XARU معها.",
             "当一项资产并不止步于买卖，运营仍在继续——XARU 亦然。"),
  "intro_sub": T("XARU can help structure its exploitation, commercialization, financial infrastructure and market access — one continuity, from the asset to the final product.",
                 "XARU puede ayudar a estructurar su explotación, comercialización, infraestructura financiera y acceso a mercado — una sola continuidad, del activo al producto final.",
                 "يمكن أن تساعد XARU في هيكلة استغلاله وتسويقه وبنيته المالية ووصوله إلى السوق — استمرارية واحدة، من الأصل إلى المنتج النهائي.",
                 "XARU 可协助架构其开发利用、商业化、金融基础设施与市场准入——从资产到最终产品，一以贯之。"),
  "01": _P(p=[T(
    "Not every asset XARU works with ends at a sale. A quarry keeps producing; a farm keeps harvesting; an international operation keeps paying, collecting and reconciling. Trade & Financial Infrastructure is the continuity of the same discipline: when a productive asset must be exploited, commercialized or connected to buyers, XARU structures that route; and when an international operation needs payment flows, reconciliation or purpose-built platforms, XARU designs, integrates and coordinates financial and technological infrastructure, working with authorised entities and providers where the activity requires it.",
    "No todo activo con el que trabaja XARU termina en una compraventa. Una cantera sigue produciendo; un proyecto agrícola sigue cosechando; una operación internacional sigue pagando, cobrando y conciliando. Trade & Financial Infrastructure es la continuidad de la misma disciplina: cuando un activo productivo debe explotarse, comercializarse o conectarse con compradores, XARU estructura esa ruta; y cuando una operación internacional necesita flujos de pago, conciliación o plataformas a medida, XARU diseña, integra y coordina infraestructura financiera y tecnológica, trabajando con entidades y proveedores autorizados cuando la actividad lo requiere.",
    "ليس كل أصل تعمل عليه XARU ينتهي عند صفقة بيع. فالمحجر يواصل الإنتاج؛ والمشروع الزراعي يواصل الحصاد؛ والعملية الدولية تواصل الدفع والتحصيل والتسوية. «التجارة والبنية المالية» هي استمرارية الانضباط نفسه: عندما يجب استغلال أصل إنتاجي أو تسويقه أو ربطه بالمشترين، تُهيكل XARU ذلك المسار؛ وعندما تحتاج عملية دولية إلى تدفقات دفع أو تسوية أو منصات مخصّصة، تصمّم XARU وتُدمج وتنسّق البنية المالية والتقنية، بالعمل مع كيانات ومزوّدين مرخّصين عندما يستلزم النشاط ذلك.",
    "并非 XARU 经手的每项资产都止于一笔交易。采石场持续出产；农业项目持续收获；国际运营持续付款、收款与对账。贸易与金融基础设施是同一纪律的延续：当生产性资产需要开发、商业化或对接买家时，XARU 架构这条路径；当国际运营需要支付流程、对账或定制平台时，XARU 设计、整合并协调金融与技术基础设施，并在业务需要时与获授权的实体及服务商合作。")]),
  "02": _P(p=[T("Those for whom the transaction was only the beginning of the operation.",
                "Aquellos para quienes la transacción fue solo el comienzo de la operación.",
                "من كانت الصفقة بالنسبة إليهم مجرّد بداية العملية.",
                "对其而言，交易只是运营开端的各方。")],
           list=[T("Holders of mining licences, quarries and exploitation rights", "Titulares de licencias mineras, canteras y derechos de explotación", "حاملو رخص التعدين والمحاجر وحقوق الاستغلال", "矿业许可、采石场与开采权的持有人"),
                 T("Owners of agricultural projects, productive units and industrial assets", "Propietarios de proyectos agrícolas, unidades productivas y activos industriales", "ملّاك المشاريع الزراعية والوحدات الإنتاجية والأصول الصناعية", "农业项目、生产单元与工业资产的业主"),
                 T("Producers with available production seeking buyers, offtake or distribution", "Productores con producción disponible que buscan compradores, offtake o distribución", "منتجون لديهم إنتاج متاح يبحثون عن مشترين أو اتفاقيات شراء مسبق أو توزيع", "拥有可供产量、寻求买家、承购或分销的生产方"),
                 T("Buyers seeking verified production and international placement", "Compradores que buscan producción verificada y colocación internacional", "مشترون يبحثون عن إنتاج موثّق وتصريف دولي", "寻求经核实产量与国际配售的买家"),
                 T("Companies whose international operations need payment flows, reconciliation or purpose-built platforms", "Compañías cuyas operaciones internacionales necesitan flujos de pago, conciliación o plataformas a medida", "شركات تحتاج عملياتها الدولية إلى تدفقات دفع أو تسوية أو منصات مخصّصة", "其国际运营需要支付流程、对账或定制平台的企业")]),
  "03": _P(p=[T("One division, two subdivisions — the productive asset, and the infrastructure that lets it operate internationally.",
                "Una división, dos subdivisiones — el activo productivo, y la infraestructura que le permite operar internacionalmente.",
                "قسم واحد وفرعان — الأصل الإنتاجي، والبنية التي تتيح له العمل دولياً.",
                "一个板块、两个分部——生产性资产，以及使其得以国际化运营的基础设施。")],
           cols=[
             {"h": T("A — Productive assets & commodities",
                     "A — Activos productivos y commodities",
                     "أ — الأصول الإنتاجية والسلع",
                     "A——生产性资产与大宗商品"),
              "cta": T("View a current teaser", "Ver un teaser actual", "اطّلع على موجز حالي", "查看当前简报"),
              "href": "opportunities/pa-quarry-license/",
              "items": [T("Mining licences and quarries", "Licencias mineras y canteras", "رخص التعدين والمحاجر", "矿业许可与采石场"),
                        T("Agricultural projects and productive units", "Proyectos agrícolas y unidades productivas", "المشاريع الزراعية والوحدات الإنتاجية", "农业项目与生产单元"),
                        T("Industrial assets and exploitation rights", "Activos industriales y derechos de explotación", "الأصول الصناعية وحقوق الاستغلال", "工业资产与开采权"),
                        T("Available production and verified buyers", "Producción disponible y compradores verificados", "الإنتاج المتاح والمشترون الموثّقون", "可供产量与经核实的买家"),
                        T("Offtake and structured placement", "Offtake y colocación estructurada", "اتفاقيات الشراء المسبق والتصريف المنظّم", "承购与结构化配售"),
                        T("Distribution and international placement", "Distribución y colocación internacional", "التوزيع والتصريف الدولي", "分销与国际配售"),
                        T("Two-way route: buyer ↔ seller, from the asset to the final product", "Doble vía: comprador ↔ vendedor, del activo al producto final", "مسار ثنائي الاتجاه: مشترٍ ↔ بائع، من الأصل إلى المنتج النهائي", "双向路径：买家 ↔ 卖家，从资产到最终产品")]},
             {"h": T("B — Financial & technological infrastructure",
                     "B — Infraestructura financiera y tecnológica",
                     "ب — البنية المالية والتقنية",
                     "B——金融与技术基础设施"),
              "cta": T("Discuss an operation", "Plantear una operación", "ناقش عملية", "洽谈业务"),
              "href": "private-enquiry/",
              "items": [T("Payment-flow design and multi-currency orchestration", "Diseño de flujos de pago y orquestación multidivisa", "تصميم تدفقات الدفع وتنسيق العملات المتعددة", "支付流程设计与多币种编排"),
                        T("Integration of regulated providers", "Integración de proveedores regulados", "دمج المزوّدين الخاضعين للتنظيم", "受监管服务商的整合"),
                        T("Wallet infrastructure, ledgers and reconciliation", "Wallet infrastructure, ledgers y conciliación", "بنية المحافظ ودفاتر الأستاذ والتسوية", "钱包基础设施、账本与对账"),
                        T("Payouts, collections and settlement flows", "Payouts, collections y flujos de liquidación", "المدفوعات الصادرة والتحصيلات وتدفقات التسوية", "付款、收款与结算流程"),
                        T("APIs, back office and reporting", "APIs, backoffice y reporting", "واجهات API والمكتب الخلفي والتقارير", "API、后台与报表"),
                        T("Onboarding and KYC / AML integration", "Onboarding e integración KYC / AML", "تسجيل العملاء ودمج إجراءات اعرف عميلك / مكافحة الغسل", "客户接入与 KYC / AML 集成"),
                        T("Purpose-built tools and proprietary platform development", "Herramientas a medida y desarrollo de plataformas propias", "أدوات مخصّصة وتطوير منصات خاصة", "定制工具与自有平台开发")]}]),
  "04": _P(p=[T(
    "On the productive side, XARU validates the asset and its licences, structures exploitation and commercialization, and runs the two-way route between production and demand — from offtake to distribution and international placement — under the same verification discipline as any XARU mandate. On the infrastructure side, XARU designs, integrates and coordinates financial and technological infrastructure for international operations. Three things are never confused: technology developed by XARU or its companies; services XARU provides directly; and regulated services, which are provided by authorised entities or partners. Every proposal states, in writing, which is which.",
    "En el lado productivo, XARU valida el activo y sus licencias, estructura la explotación y la comercialización, y conduce la doble vía entre producción y demanda — del offtake a la distribución y la colocación internacional — bajo la misma disciplina de verificación que cualquier mandato de XARU. En el lado de infraestructura, XARU diseña, integra y coordina infraestructura financiera y tecnológica para operaciones internacionales. Tres cosas nunca se confunden: la tecnología desarrollada por XARU o sus empresas; los servicios que XARU presta directamente; y los servicios regulados, que prestan entidades o partners autorizados. Cada propuesta establece por escrito qué es cada cosa.",
    "في الجانب الإنتاجي، تتحقّق XARU من الأصل وتراخيصه، وتُهيكل الاستغلال والتسويق، وتدير المسار الثنائي بين الإنتاج والطلب — من اتفاقيات الشراء المسبق إلى التوزيع والتصريف الدولي — وفق انضباط التحقّق ذاته في كل تفويض لدى XARU. وفي جانب البنية، تصمّم XARU وتُدمج وتنسّق البنية المالية والتقنية للعمليات الدولية. ثلاثة أمور لا تختلط أبداً: التقنية التي تطوّرها XARU أو شركاتها؛ والخدمات التي تقدّمها XARU مباشرةً؛ والخدمات الخاضعة للتنظيم التي تقدّمها كيانات أو شركاء مرخّصون. وكل عرض يحدّد كتابةً ما ينتمي إلى كلٍّ منها.",
    "在生产性资产一侧，XARU 核验资产及其许可，架构开发利用与商业化，并按照 XARU 每项委托同样的核实纪律，运作产量与需求之间的双向路径——从承购到分销与国际配售。在基础设施一侧，XARU 为国际运营设计、整合并协调金融与技术基础设施。三件事从不混淆：XARU 或其旗下公司开发的技术；XARU 直接提供的服务；以及由获授权实体或合作伙伴提供的受监管服务。每份提案均以书面明确各自的归属。")]),
  "05": _P(p=[T("What XARU does not do.", "Qué NO hace XARU.", "ما لا تقوم به XARU.", "XARU 不做的事。")],
           list=[T("Claim to be a global financial institution — it is not, and does not present itself as one", "Afirmar que es una entidad financiera global — no lo es, y no se presenta como tal", "الادعاء بأنها مؤسسة مالية عالمية — فهي ليست كذلك ولا تقدّم نفسها على هذا النحو", "宣称自己是全球性金融机构——它不是，也从不如此自我呈现"),
                 T("Provide regulated financial services itself where the activity belongs to authorised entities or partners", "Prestar por sí misma servicios financieros regulados cuando la actividad corresponde a entidades o partners autorizados", "تقديم خدمات مالية خاضعة للتنظيم بنفسها حيث يعود النشاط إلى كيانات أو شركاء مرخّصين", "在业务属于获授权实体或合作伙伴的领域，自行提供受监管的金融服务"),
                 T("Present partner-provided regulated services as its own", "Presentar como propios los servicios regulados prestados por partners", "عرض الخدمات المنظّمة التي يقدّمها الشركاء على أنها خدماتها", "把合作伙伴提供的受监管服务当作自有服务呈现"),
                 T("Publish licences, volumes, coordinates or production data without a mandate and an NDA", "Publicar licencias, volúmenes, coordenadas o datos de producción sin mandato y sin NDA", "نشر التراخيص أو الأحجام أو الإحداثيات أو بيانات الإنتاج دون تفويض واتفاقية سرية", "在无委托与保密协议的情况下公布许可、产量、坐标或生产数据"),
                 T("Broker production whose title, licence or origin has not been verified", "Intermediar producción cuya titularidad, licencia u origen no han sido verificados", "التوسّط في إنتاج لم يُتحقّق من ملكيته أو ترخيصه أو منشئه", "为产权、许可或来源未经核实的产量进行中介")]),
  "06": _P(p=[T("Ten steps, one discipline — whether the mandate concerns a quarry or a payment flow.",
                "Diez pasos, una sola disciplina — sea el mandato una cantera o un flujo de pagos.",
                "عشر خطوات وانضباط واحد — سواء كان التفويض محجراً أو تدفّق مدفوعات.",
                "十个步骤、同一纪律——无论委托对象是采石场还是支付流程。")],
           steps=[T("Structured intake", "Intake estructurado", "استقبال منظّم", "结构化登记"),
                  T("Verification of title, licence or capability", "Verificación de titularidad, licencia o capacidad", "التحقّق من الملكية أو الترخيص أو القدرة", "核实产权、许可或能力"),
                  T("NDA", "NDA", "اتفاقية سرية", "保密协议"),
                  T("KYC / AML through regulated channels where applicable", "KYC / AML por canales regulados cuando corresponda", "اعرف عميلك / مكافحة الغسل عبر قنوات منظّمة عند الاقتضاء", "适用时通过受监管渠道进行 KYC / AML"),
                  T("Technical, legal and commercial review", "Revisión técnica, legal y comercial", "المراجعة الفنية والقانونية والتجارية", "技术、法律与商业审查"),
                  T("Structuring — offtake, placement or flow design", "Estructuración — offtake, colocación o diseño de flujos", "الهيكلة — الشراء المسبق أو التصريف أو تصميم التدفقات", "架构——承购、配售或流程设计"),
                  T("Counterparty or provider matching", "Encaje de contrapartes o proveedores", "مواءمة الأطراف المقابلة أو المزوّدين", "对手方或服务商匹配"),
                  T("Integration and execution", "Integración y ejecución", "التكامل والتنفيذ", "整合与执行"),
                  T("Reporting and reconciliation", "Reporting y conciliación", "التقارير والتسوية", "报表与对账"),
                  T("Continuity and follow-through", "Continuidad y seguimiento", "الاستمرارية والمتابعة", "延续与跟进")]),
  "07": _P(p=[T("Admission protects the production, the buyers and the operation alike.",
                "La admisión protege por igual a la producción, a los compradores y a la operación.",
                "القبول يحمي الإنتاج والمشترين والعملية على حدّ سواء.",
                "准入同等保护产量、买家与运营。")],
           list=[T("Verifiable title, licence or exploitation right over the asset or production", "Titularidad, licencia o derecho de explotación verificables sobre el activo o la producción", "ملكية أو ترخيص أو حق استغلال قابل للتحقّق على الأصل أو الإنتاج", "对资产或产量具有可核验的产权、许可或开采权"),
                 T("Verifiable purchasing capacity or operating capability on the demand side", "Capacidad de compra o capacidad operativa verificables del lado de la demanda", "قدرة شرائية أو تشغيلية قابلة للتحقّق في جانب الطلب", "需求侧具有可核验的购买或运营能力"),
                 T("A defined operation — not a speculative enquiry", "Una operación definida — no una consulta especulativa", "عملية محدّدة — لا استفسار مضاربي", "明确的业务——而非投机性询问"),
                 T("Acceptance of NDA, KYC / AML and documented sequence", "Aceptación de NDA, KYC / AML y secuencia documentada", "قبول اتفاقية السرية واعرف عميلك / مكافحة الغسل والتسلسل المُوثَّق", "接受保密协议、KYC / AML 与有据可查的流程")]),
  "08": _P(p=[T("Three layers, stated plainly: technology developed by XARU or its companies; services provided directly; and regulated services provided by authorised entities and partners. The layer never changes the discipline — only who is authorised to act.",
                "Tres capas, dichas con claridad: tecnología desarrollada por XARU o sus empresas; servicios prestados directamente; y servicios regulados prestados por entidades y partners autorizados. La capa nunca cambia la disciplina — solo quién está autorizado a actuar.",
                "ثلاث طبقات معلنة بوضوح: تقنية تطوّرها XARU أو شركاتها؛ وخدمات تُقدَّم مباشرةً؛ وخدمات منظّمة تقدّمها كيانات وشركاء مرخّصون. الطبقة لا تغيّر الانضباط أبداً — بل من هو المخوَّل بالتصرّف.",
                "三个层级，直言不讳：XARU 或其旗下公司开发的技术；直接提供的服务；以及由获授权实体与合作伙伴提供的受监管服务。层级从不改变纪律——只决定谁获授权行事。")],
           list=[T("In-house design and development of platforms, tools and integrations by XARU companies", "Diseño y desarrollo propios de plataformas, herramientas e integraciones por empresas de XARU", "تصميم وتطوير داخليان للمنصات والأدوات والتكاملات عبر شركات XARU", "由 XARU 旗下公司自主设计与开发平台、工具及集成"),
                 T("In-house structuring, verification and commercial coordination", "Estructuración, verificación y coordinación comercial propias", "هيكلة وتحقّق وتنسيق تجاري داخلي", "自有架构、核实与商业协调"),
                 T("Regulated payment, custody and financial services through authorised entities and partners", "Servicios regulados de pago, custodia y financieros a través de entidades y partners autorizados", "خدمات الدفع والحفظ والخدمات المالية المنظّمة عبر كيانات وشركاء مرخّصين", "通过获授权实体与合作伙伴提供受监管的支付、托管与金融服务"),
                 T("Legal, tax and trade specialists by jurisdiction", "Especialistas legales, fiscales y de comercio por jurisdicción", "مختصون قانونيون وضريبيون وتجاريون بحسب الولاية القضائية", "按司法管辖区配置的法律、税务与贸易专家")]),
  "09": _P(p=[T(
    "The holder of a quarry licence, with permits in place and production available, needs buyers — and the infrastructure to collect internationally. XARU validates the licence and the counterparty, publishes a teaser without volumes or coordinates, verifies buyers under NDA and KYC, structures the offtake, and designs the collection and settlement flows with authorised providers. The asset did not end at a sale: it became an operating route from quarry to buyer, reconciled every month.",
    "El titular de una licencia de cantera, con permisos vigentes y producción disponible, necesita compradores — y la infraestructura para cobrar internacionalmente. XARU valida la licencia y la contraparte, publica un teaser sin volúmenes ni coordenadas, verifica compradores bajo NDA y KYC, estructura el offtake y diseña los flujos de cobro y liquidación con proveedores autorizados. El activo no terminó en una compraventa: se convirtió en una ruta operativa de la cantera al comprador, conciliada cada mes.",
    "يحتاج حامل رخصة محجر، بتصاريح سارية وإنتاج متاح، إلى مشترين — وإلى البنية اللازمة للتحصيل دولياً. تتحقّق XARU من الرخصة والطرف المقابل، وتنشر موجزاً دون أحجام أو إحداثيات، وتتحقّق من المشترين بموجب اتفاقية سرية وإجراءات اعرف عميلك، وتُهيكل اتفاق الشراء المسبق، وتصمّم تدفقات التحصيل والتسوية مع مزوّدين مرخّصين. لم ينتهِ الأصل عند صفقة بيع: بل صار مساراً تشغيلياً من المحجر إلى المشتري، يُسوَّى شهرياً.",
    "一位采石许可持有人，许可齐备、产量可供，需要买家——也需要跨境收款的基础设施。XARU 核验许可与对手方，发布不含产量与坐标的简报，在保密协议与 KYC 之下核实买家，架构承购安排，并与获授权服务商设计收款与结算流程。这项资产没有止于一笔买卖：它成为一条由采石场通往买家、按月对账的运营路径。")]),
  "10": _P(p=[T("Digital-asset and payment-related activity, where it arises, is conducted exclusively through regulated channels, with full KYC / AML verification. Nothing is presented as licensed, produced or contracted unless it has been verified under the mandate — and no regulated service is ever presented as XARU's own where it is provided by an authorised entity or partner.",
                "La actividad relacionada con activos digitales y pagos, cuando surge, se realiza exclusivamente a través de canales regulados, con verificación KYC / AML completa. Nada se presenta como licenciado, producido o contratado si no ha sido verificado bajo el mandato — y ningún servicio regulado se presenta jamás como propio de XARU cuando lo presta una entidad o partner autorizado.",
                "الأنشطة المتصلة بالأصول الرقمية والمدفوعات، حيثما نشأت، تُجرى حصراً عبر قنوات منظّمة مع تحقّق كامل وفق «اعرف عميلك» ومكافحة غسل الأموال. لا يُعرَض شيء على أنه مرخّص أو مُنتَج أو متعاقَد عليه ما لم يُتحقّق منه بموجب التفويض — ولا تُعرَض أي خدمة منظّمة على أنها خدمة XARU حين يقدّمها كيان أو شريك مرخّص.",
                "涉及数字资产与支付的活动（如有）一律通过受监管渠道进行，并完成完整的 KYC / AML 核验。凡未经委托核实之事项，一律不以已持牌、已生产或已签约的名义呈现——凡由获授权实体或合作伙伴提供的受监管服务，也绝不以 XARU 自有服务的名义呈现。")]),
  "11": _P(faq=[
    (T("Is XARU a bank or a global financial institution?", "¿XARU es un banco o una entidad financiera global?", "هل XARU مصرف أو مؤسسة مالية عالمية؟", "XARU 是银行或全球性金融机构吗？"),
     T("No. XARU designs, integrates and coordinates financial and technological infrastructure for international operations, working with authorised entities and providers where the activity requires it.",
       "No. XARU diseña, integra y coordina infraestructura financiera y tecnológica para operaciones internacionales, trabajando con entidades y proveedores autorizados cuando la actividad lo requiere.",
       "لا. تصمّم XARU وتُدمج وتنسّق البنية المالية والتقنية للعمليات الدولية، بالعمل مع كيانات ومزوّدين مرخّصين عندما يستلزم النشاط ذلك.",
       "不是。XARU 为国际运营设计、整合并协调金融与技术基础设施，并在业务需要时与获授权的实体及服务商合作。")),
    (T("Do you publish volumes, licences or coordinates of productive assets?", "¿Publican volúmenes, licencias o coordenadas de los activos productivos?", "هل تنشرون أحجام الأصول الإنتاجية أو تراخيصها أو إحداثياتها؟", "你们会公布生产性资产的产量、许可或坐标吗？"),
     T("No. Productive assets are shown as teasers only — region, category, scale and status. Everything else is released under NDA, through the Private Deal Room route.",
       "No. Los activos productivos se muestran solo como teasers — región, categoría, escala y estado. Todo lo demás se libera bajo NDA, a través de la ruta del Private Deal Room.",
       "لا. تُعرَض الأصول الإنتاجية كموجزات فقط — المنطقة والفئة والحجم والحالة. وكل ما عدا ذلك يُتاح بموجب اتفاقية سرية عبر مسار غرفة الصفقات الخاصة.",
       "不会。生产性资产仅以简报形式展示——地区、类别、规模与状态。其余一切均在保密协议下、经私人交易室路径披露。")),
    (T("Who provides the regulated services in a payment operation?", "¿Quién presta los servicios regulados en una operación de pagos?", "من يقدّم الخدمات المنظّمة في عملية مدفوعات؟", "支付业务中的受监管服务由谁提供？"),
     T("Authorised entities and partners, always. XARU designs the architecture, integrates the providers and coordinates the operation — and every proposal states in writing which layer each element belongs to.",
       "Entidades y partners autorizados, siempre. XARU diseña la arquitectura, integra a los proveedores y coordina la operación — y cada propuesta establece por escrito a qué capa pertenece cada elemento.",
       "كيانات وشركاء مرخّصون، دائماً. تصمّم XARU البنية وتُدمج المزوّدين وتنسّق العملية — ويحدّد كل عرض كتابةً الطبقة التي ينتمي إليها كل عنصر.",
       "始终由获授权的实体与合作伙伴提供。XARU 设计架构、整合服务商并协调运营——每份提案均以书面明确每个环节所属的层级。")),
   ]),
 },

 # ---------------------------------------------------------------- Corporate Services & Relocation
 "business-infrastructure/corporate-services": {
  "intro": T("International establishment is not a visa — it is a structure.",
             "El establecimiento internacional no es un visado — es una estructura.",
             "التأسيس الدولي ليس تأشيرة — بل بنية.",
             "国际落地不是一纸签证——而是一套架构。"),
  "intro_sub": T("Company, government, tax, accounting, compliance, banking, operation, residency, family, continuity — one cycle, provided directly or coordinated by jurisdiction.",
                 "Empresa, gobierno, fiscalidad, contabilidad, cumplimiento, banca, operación, residencia, familia, continuidad — un solo ciclo, prestado directamente o coordinado según la jurisdicción.",
                 "الشركة والحوكمة والضرائب والمحاسبة والامتثال والمصارف والتشغيل والإقامة والعائلة والاستمرارية — دورة واحدة، تُقدَّم مباشرةً أو بالتنسيق بحسب الولاية القضائية.",
                 "公司、治理、税务、会计、合规、银行、运营、居留、家庭、延续——一个完整周期，视司法管辖区直接提供或协调完成。"),
  "01": _P(p=[T(
    "XARU HOME establishes companies and families in new jurisdictions — completely. Not a visa application, but the full cycle behind a working international presence: the entity, its governance, its tax and accounting order, its compliance, its banking, its office and payroll, the residency of its principals, the installation of their family, and the administration that keeps all of it standing year after year. Depending on the jurisdiction, XARU provides each service directly or coordinates it, always with specialised legal counsel in each jurisdiction.",
    "XARU HOME establece compañías y familias en nuevas jurisdicciones — por completo. No una solicitud de visado, sino el ciclo entero que sostiene una presencia internacional operativa: la entidad, su gobierno, su orden fiscal y contable, su cumplimiento, su banca, su oficina y su nómina, la residencia de sus principales, la instalación de su familia, y la administración que mantiene todo en pie año tras año. Según la jurisdicción, XARU presta cada servicio directamente o lo coordina, siempre con asesoría legal especializada en cada jurisdicción.",
    "تؤسّس XARU HOME الشركات والعائلات في ولايات قضائية جديدة — تأسيساً كاملاً. ليس طلب تأشيرة، بل الدورة الكاملة التي يقوم عليها حضور دولي عامل: الكيان وحوكمته ونظامه الضريبي والمحاسبي وامتثاله وخدماته المصرفية ومكتبه ورواتبه، وإقامة مالكيه، واستقرار عائلاتهم، والإدارة التي تُبقي ذلك كله قائماً عاماً بعد عام. بحسب الولاية القضائية، تقدّم XARU كل خدمة مباشرةً أو تنسّقها، ودائماً مع مستشارين قانونيين متخصّصين في كل ولاية قضائية.",
    "XARU HOME 帮助企业与家庭在新的司法管辖区完整落地。不是一份签证申请，而是支撑一个有效国际存在的完整周期：实体及其治理、税务与会计秩序、合规、银行、办公室与薪酬体系、负责人的居留、家人的安置，以及让这一切年复一年稳固运转的行政管理。视司法管辖区而定，XARU 直接提供或协调每项服务，且始终与各司法管辖区的专业法律顾问协同。")]),
  "02": _P(p=[T("Companies that must operate, and families that must live — often at the same time.",
                "Compañías que deben operar, y familias que deben vivir — a menudo al mismo tiempo.",
                "شركات يجب أن تعمل، وعائلات يجب أن تستقرّ — وغالباً في آنٍ واحد.",
                "需要运营的企业，与需要安家的家庭——往往同时进行。")],
           list=[T("Companies entering a new jurisdiction", "Compañías que entran en una nueva jurisdicción", "شركات تدخل ولاية قضائية جديدة", "进入新司法管辖区的企业"),
                 T("Owners and investors establishing after a transaction", "Propietarios e inversionistas que se establecen tras una transacción", "ملّاك ومستثمرون يؤسّسون بعد صفقة", "交易完成后进行落地的业主与投资者"),
                 T("Executives and principals relocating with their families", "Ejecutivos y principales que se relocalizan con sus familias", "تنفيذيون ومالكون ينتقلون مع عائلاتهم", "携家人迁居的高管与企业主"),
                 T("Family offices ordering a multi-jurisdictional presence", "Family offices que ordenan una presencia multijurisdiccional", "مكاتب عائلية تنظّم حضوراً متعدد الولايات القضائية", "统筹多司法管辖区布局的家族办公室")]),
  "03": _P(p=[T("Two journeys, one calendar. The company lands; the family lands. XARU runs both — separately when needed, together when they belong together.",
                "Dos recorridos, un solo calendario. La empresa aterriza; la familia aterriza. XARU conduce ambos — por separado cuando hace falta, juntos cuando se pertenecen.",
                "مساران وجدول واحد. تستقرّ الشركة؛ وتستقرّ العائلة. تدير XARU المسارين — منفصلَين عند الحاجة، ومعاً حين يكونان متلازمين.",
                "两条路径，一份日程。企业落地；家庭安家。XARU 同时驾驭两者——需要时分开推进，应当时合并推进。")],
           cols=[
             {"h": T("Corporate Landing", "Corporate Landing", "الاستقرار المؤسسي (Corporate Landing)", "企业落地（Corporate Landing）"),
              "cta": T("Begin the corporate journey", "Iniciar el recorrido corporativo", "ابدأ المسار المؤسسي", "开启企业路径"),
              "href": "private-enquiry/",
              "items": [T("Jurisdiction and entity", "Jurisdicción y entidad", "الولاية القضائية والكيان", "司法管辖区与实体"),
                        T("Licences and corporate governance", "Licencias y gobierno corporativo", "التراخيص والحوكمة المؤسسية", "牌照与公司治理"),
                        T("Accounting and tax", "Contabilidad y fiscalidad", "المحاسبة والضرائب", "会计与税务"),
                        T("Compliance and due diligence", "Cumplimiento y due diligence", "الامتثال والعناية الواجبة", "合规与尽职调查"),
                        T("Banking and operational readiness", "Banca y preparación operativa", "الخدمات المصرفية والجاهزية التشغيلية", "银行与运营准备"),
                        T("Office, payroll and operation", "Oficina, nómina y operación", "المكتب والرواتب والتشغيل", "办公室、薪酬与运营")]},
             {"h": T("Private & Family Landing", "Private & Family Landing", "الاستقرار الخاص والعائلي (Private & Family Landing)", "私人与家庭安置（Private & Family Landing）"),
              "cta": T("Begin the family journey", "Iniciar el recorrido familiar", "ابدأ المسار العائلي", "开启家庭路径"),
              "href": "private-enquiry/",
              "items": [T("Residency and migration", "Residencia y migración", "الإقامة والهجرة", "居留与移民"),
                        T("Home and housing", "Vivienda", "السكن", "住房安居"),
                        T("Schooling and education", "Escolarización y educación", "المدارس والتعليم", "入学与教育"),
                        T("Insurance and healthcare", "Seguro y salud", "التأمين والرعاية الصحية", "保险与医疗"),
                        T("Transport, staff and installation", "Transporte, personal e instalación", "التنقّل والطاقم والاستقرار", "交通、家政与安置"),
                        T("Wealth order and family continuity", "Orden patrimonial y continuidad familiar", "التنظيم الثروي والاستمرارية العائلية", "财富秩序与家族延续")]}]),
  "04": _P(p=[T("Company formation and corporate governance; legal, tax and accounting coordination; AML, compliance and due diligence; banking and operational readiness; migration and residency; family relocation; business installation; and ongoing corporate administration once everything is standing. Depending on the jurisdiction, each service is provided directly or coordinated — and always with specialised legal counsel in each jurisdiction.",
                "Constitución empresarial y gobierno corporativo; coordinación legal, fiscal y contable; AML, cumplimiento y due diligence; banca y preparación operativa; migración y residencia; relocalización familiar; instalación empresarial; y administración corporativa continua una vez que todo está en pie. Según la jurisdicción, cada servicio se presta directamente o se coordina — y siempre con asesoría legal especializada en cada jurisdicción.",
                "تأسيس الشركات والحوكمة المؤسسية؛ والتنسيق القانوني والضريبي والمحاسبي؛ ومكافحة غسل الأموال والامتثال والعناية الواجبة؛ والخدمات المصرفية والجاهزية التشغيلية؛ والهجرة والإقامة؛ وانتقال العائلة؛ والتأسيس التشغيلي للأعمال؛ والإدارة المؤسسية المستمرة بعد اكتمال كل شيء. بحسب الولاية القضائية، تُقدَّم كل خدمة مباشرةً أو بالتنسيق — ودائماً مع مستشارين قانونيين متخصّصين في كل ولاية قضائية.",
                "公司设立与公司治理；法律、税务与会计协调；反洗钱、合规与尽职调查；银行与运营准备；移民与居留；家庭迁居；企业落地安装；以及一切就绪后的持续企业行政管理。视司法管辖区而定，每项服务直接提供或协调完成——且始终与各司法管辖区的专业法律顾问协同。")]),
  "05": _P(p=[T("What XARU does not do.", "Qué NO hace XARU.", "ما لا تقوم به XARU.", "XARU 不做的事。")],
           list=[T("Operate as a visa agency — residency is one step of an establishment structure, never the product", "Operar como una agencia de visados — la residencia es un paso de una estructura de establecimiento, nunca el producto", "العمل كوكالة تأشيرات — فالإقامة خطوة ضمن بنية تأسيس، وليست المنتَج أبداً", "充当签证中介——居留只是落地架构中的一步，绝非产品本身"),
                 T("Practise law or give tax advice itself — it coordinates specialised counsel in each jurisdiction", "Ejercer la abogacía o dar asesoría fiscal por sí misma — coordina asesoría especializada en cada jurisdicción", "ممارسة المحاماة أو تقديم المشورة الضريبية بنفسها — بل تنسّق مستشارين متخصّصين في كل ولاية قضائية", "自行执业法律或提供税务意见——而是协调各司法管辖区的专业顾问"),
                 T("Guarantee residency, banking or licensing outcomes — decisions belong to authorities and institutions", "Garantizar resultados de residencia, banca o licencias — las decisiones pertenecen a autoridades e instituciones", "ضمان نتائج الإقامة أو الخدمات المصرفية أو التراخيص — فالقرارات بيد السلطات والمؤسسات", "保证居留、银行或牌照的结果——决定权属于当局与机构"),
                 T("Shortcut compliance, source-of-funds or due-diligence requirements", "Atajar los requisitos de cumplimiento, origen de fondos o due diligence", "الالتفاف على متطلبات الامتثال أو مصدر الأموال أو العناية الواجبة", "在合规、资金来源或尽调要求上走捷径")]),
  "06": _P(p=[T("The establishment cycle, in the order in which it actually happens. Not every mandate runs all ten — but every mandate knows where it stands.",
                "El ciclo de establecimiento, en el orden en que realmente ocurre. No todos los mandatos recorren los diez — pero todo mandato sabe en qué punto está.",
                "دورة التأسيس بالترتيب الذي تحدث به فعلاً. لا تمرّ كل التفويضات بالخطوات العشر — لكن كل تفويض يعرف موقعه.",
                "落地周期，按其实际发生的顺序展开。并非每项委托都走完十步——但每项委托都清楚自己所处的位置。")],
           steps=[T("Company — jurisdiction, entity, licences", "Empresa — jurisdicción, entidad, licencias", "الشركة — الولاية القضائية والكيان والتراخيص", "公司——司法管辖区、实体、牌照"),
                  T("Government — registrations and corporate governance", "Gobierno — registros y gobierno corporativo", "الحوكمة — التسجيلات والحوكمة المؤسسية", "治理——登记注册与公司治理"),
                  T("Tax — regime, substance and obligations", "Fiscalidad — régimen, sustancia y obligaciones", "الضرائب — النظام والجوهر والالتزامات", "税务——税制、实质与义务"),
                  T("Accounting — books, audit and reporting", "Contabilidad — libros, auditoría y reporting", "المحاسبة — الدفاتر والتدقيق والتقارير", "会计——账簿、审计与申报"),
                  T("Compliance — AML, due diligence, policies", "Cumplimiento — AML, due diligence, políticas", "الامتثال — مكافحة الغسل والعناية الواجبة والسياسات", "合规——反洗钱、尽调与制度"),
                  T("Banking — accounts and operational readiness", "Banca — cuentas y preparación operativa", "المصارف — الحسابات والجاهزية التشغيلية", "银行——账户与运营准备"),
                  T("Operation — office, payroll, contracts", "Operación — oficina, nómina, contratos", "التشغيل — المكتب والرواتب والعقود", "运营——办公室、薪酬、合同"),
                  T("Residency — principals and key people", "Residencia — principales y personas clave", "الإقامة — المالكون والأشخاص الرئيسيون", "居留——企业主与关键人员"),
                  T("Family — home, schooling, installation", "Familia — vivienda, escolarización, instalación", "العائلة — السكن والمدارس والاستقرار", "家庭——住房、入学与安置"),
                  T("Continuity — ongoing corporate administration", "Continuidad — administración corporativa continua", "الاستمرارية — إدارة مؤسسية مستمرة", "延续——持续的企业行政管理")]),
  "07": _P(p=[T("Establishment succeeds when the client's position is as verifiable as the structure built around it.",
                "El establecimiento funciona cuando la posición del cliente es tan verificable como la estructura que se construye a su alrededor.",
                "ينجح التأسيس عندما تكون وضعية العميل قابلة للتحقّق كما البنية المبنية حولها.",
                "唯有当客户的状况与围绕其构建的架构同样可核验时，落地方能成功。")],
           list=[T("Verifiable identity, ownership and source of funds", "Identidad, titularidad y origen de fondos verificables", "هوية وملكية ومصدر أموال قابلة للتحقّق", "可核验的身份、所有权与资金来源"),
                 T("A real operation or presence to establish — not a shell for its own sake", "Una operación o presencia real que establecer — no una sociedad vacía por sí misma", "عملية أو حضور حقيقي يُراد تأسيسه — لا كيان صوري لذاته", "有真实的运营或存在需要落地——而非为空壳而空壳"),
                 T("Willingness to complete KYC / AML and jurisdiction requirements", "Disposición a completar KYC / AML y los requisitos de la jurisdicción", "الاستعداد لاستكمال متطلبات اعرف عميلك / مكافحة الغسل ومتطلبات الولاية القضائية", "愿意完成 KYC / AML 及所在司法管辖区的要求"),
                 T("Acceptance of realistic timelines set by authorities and institutions", "Aceptación de plazos realistas fijados por autoridades e instituciones", "قبول جداول زمنية واقعية تحدّدها السلطات والمؤسسات", "接受由当局与机构决定的现实时间表")]),
  "08": _P(p=[T("Establishment coordination in-house; regulated corporate services through authorised entities where the jurisdiction requires it; and specialised legal, tax and immigration counsel in each jurisdiction.",
                "Coordinación de establecimiento propia; servicios corporativos regulados a través de entidades autorizadas cuando la jurisdicción lo requiere; y asesoría legal, fiscal y migratoria especializada en cada jurisdicción.",
                "تنسيق تأسيس داخلي؛ وخدمات مؤسسية منظّمة عبر كيانات مرخّصة حيثما تستلزم الولاية القضائية ذلك؛ ومستشارون متخصّصون في القانون والضرائب والهجرة في كل ولاية قضائية.",
                "落地协调由自有团队完成；在司法管辖区有要求时，受监管的企业服务经由获授权实体提供；并在各司法管辖区配备专业的法律、税务与移民顾问。")],
           list=[T("In-house establishment management — one calendar, one responsible team", "Gestión de establecimiento propia — un calendario, un equipo responsable", "إدارة تأسيس داخلية — جدول واحد وفريق مسؤول واحد", "自有落地管理——一份日程，一个负责团队"),
                 T("Corporate service capabilities through authorised entities where required", "Capacidades de servicios corporativos a través de entidades autorizadas cuando se requiere", "قدرات خدمات مؤسسية عبر كيانات مرخّصة عند الاقتضاء", "在需要时通过获授权实体提供企业服务能力"),
                 T("Specialised legal, tax and immigration counsel by jurisdiction", "Asesoría legal, fiscal y migratoria especializada por jurisdicción", "مستشارون قانونيون وضريبيون ومختصون بالهجرة بحسب الولاية القضائية", "按司法管辖区配置的专业法律、税务与移民顾问"),
                 T("Banking, insurance, education and installation partners", "Partners de banca, seguros, educación e instalación", "شركاء في المصارف والتأمين والتعليم والاستقرار", "银行、保险、教育与安置合作伙伴")]),
  "09": _P(p=[T(
    "A family company acquires an operating asset abroad and must now exist there. XARU sequences the entity, its licences, accounting, compliance and banking; the office opens and payroll runs; in parallel, residency is filed for the principals, a home is secured, the children are enrolled, and insurance and staff are in place — one calendar, one responsible team, with specialised legal counsel in the jurisdiction at every regulated step. A year later, the same team still administers the structure.",
    "Una empresa familiar adquiere un activo en operación en el extranjero y ahora debe existir allí. XARU secuencia la entidad, sus licencias, contabilidad, cumplimiento y banca; la oficina abre y la nómina corre; en paralelo, se tramita la residencia de los principales, se asegura una vivienda, se escolariza a los hijos, y el seguro y el personal quedan en su lugar — un calendario, un equipo responsable, con asesoría legal especializada en la jurisdicción en cada paso regulado. Un año después, el mismo equipo sigue administrando la estructura.",
    "تقتني شركة عائلية أصلاً تشغيلياً في الخارج وعليها الآن أن توجد هناك. ترتّب XARU الكيان وتراخيصه والمحاسبة والامتثال والخدمات المصرفية؛ يفتتح المكتب وتجري الرواتب؛ وبالتوازي يُقدَّم طلب إقامة المالكين، ويُؤمَّن سكن، ويُسجَّل الأبناء في المدارس، ويُرتَّب التأمين والطاقم — جدول واحد وفريق مسؤول واحد، مع مستشارين قانونيين متخصّصين في الولاية القضائية عند كل خطوة منظّمة. وبعد عام، لا يزال الفريق نفسه يدير البنية.",
    "一家家族企业在海外收购了一处运营资产，现在必须在当地真实存在。XARU 依序落实实体、牌照、会计、合规与银行；办公室启用，薪酬开始发放；与此同时，为企业主申请居留、落实住房、安排子女入学，保险与家政人员一一到位——一份日程，一个负责团队，每个受监管环节均有当地专业法律顾问协同。一年之后，仍是同一团队在管理这套架构。")]),
  "10": _P(p=[T("Every establishment mandate is governed by verified identity, source-of-funds and due-diligence requirements, jurisdiction-specific compliance, and confidentiality. Regulated corporate services are provided through authorised entities where the jurisdiction requires it, and every regulated step is taken with specialised legal counsel in that jurisdiction.",
                "Cada mandato de establecimiento se rige por identidad verificada, requisitos de origen de fondos y due diligence, cumplimiento específico de cada jurisdicción y confidencialidad. Los servicios corporativos regulados se prestan a través de entidades autorizadas cuando la jurisdicción lo requiere, y cada paso regulado se da con asesoría legal especializada en esa jurisdicción.",
                "يخضع كل تفويض تأسيس لهوية موثّقة ومتطلبات مصدر الأموال والعناية الواجبة والامتثال الخاص بكل ولاية قضائية والسرّية. تُقدَّم الخدمات المؤسسية المنظّمة عبر كيانات مرخّصة حيثما تستلزم الولاية القضائية ذلك، وتُتَّخذ كل خطوة منظّمة مع مستشارين قانونيين متخصّصين في تلك الولاية القضائية.",
                "每项落地委托均受以下约束：经核实的身份、资金来源与尽调要求、各司法管辖区的专项合规以及保密义务。在司法管辖区有要求时，受监管的企业服务经由获授权实体提供；每个受监管环节均在该司法管辖区专业法律顾问的协同下进行。")]),
  "11": _P(faq=[
    (T("Is XARU a visa agency?", "¿XARU es una agencia de visados?", "هل XARU وكالة تأشيرات؟", "XARU 是签证中介吗？"),
     T("No. Residency is one step of a ten-stage establishment cycle — company, government, tax, accounting, compliance, banking, operation, residency, family, continuity.",
       "No. La residencia es un paso de un ciclo de establecimiento de diez etapas — empresa, gobierno, fiscalidad, contabilidad, cumplimiento, banca, operación, residencia, familia, continuidad.",
       "لا. الإقامة خطوة واحدة ضمن دورة تأسيس من عشر مراحل — الشركة والحوكمة والضرائب والمحاسبة والامتثال والمصارف والتشغيل والإقامة والعائلة والاستمرارية.",
       "不是。居留只是十阶段落地周期中的一步——公司、治理、税务、会计、合规、银行、运营、居留、家庭、延续。")),
    (T("Who does the legal and tax work?", "¿Quién hace el trabajo legal y fiscal?", "من يتولى العمل القانوني والضريبي؟", "法律与税务工作由谁完成？"),
     T("Specialised counsel in each jurisdiction, coordinated by XARU. Depending on the jurisdiction, services are provided directly or coordinated — the responsibility for the calendar stays with XARU.",
       "Asesoría especializada en cada jurisdicción, coordinada por XARU. Según la jurisdicción, los servicios se prestan directamente o se coordinan — la responsabilidad del calendario permanece en XARU.",
       "مستشارون متخصّصون في كل ولاية قضائية، بتنسيق من XARU. بحسب الولاية القضائية، تُقدَّم الخدمات مباشرةً أو بالتنسيق — وتبقى مسؤولية الجدول الزمني لدى XARU.",
       "由各司法管辖区的专业顾问完成，XARU 负责协调。视司法管辖区而定，服务直接提供或协调完成——日程的责任始终在 XARU。")),
    (T("Can the corporate and family journeys run at the same time?", "¿Los recorridos corporativo y familiar pueden avanzar al mismo tiempo?", "هل يمكن أن يسير المساران المؤسسي والعائلي معاً؟", "企业与家庭两条路径可以同时推进吗？"),
     T("Yes — that is the point. Two journeys, one calendar, one responsible team: the company lands while the family lands.",
       "Sí — de eso se trata. Dos recorridos, un solo calendario, un solo equipo responsable: la empresa aterriza mientras la familia aterriza.",
       "نعم — وهذا هو المقصود. مساران وجدول واحد وفريق مسؤول واحد: تستقرّ الشركة بينما تستقرّ العائلة.",
       "可以——这正是关键所在。两条路径、一份日程、一个负责团队：企业落地的同时，家庭安家。")),
   ]),
 },
}

# ================================================================ Business Infrastructure door page
BI_DOOR = {
 "lead": T("The foundations that support the operation. What XARU acquires, structures and finances must also work: produce, trade, pay, comply and exist — legally, fiscally and operationally.",
           "Los cimientos que soportan la operación. Lo que XARU adquiere, estructura y financia también debe funcionar: producir, comerciar, pagar, cumplir y existir — legal, fiscal y operativamente.",
           "الأسس التي تسند العملية. ما تقتنيه XARU وتُهيكله وتموّله يجب أن يعمل أيضاً: أن يُنتج ويتاجر ويدفع ويمتثل ويوجد — قانونياً وضريبياً وتشغيلياً.",
           "支撑运营的基石。XARU 所收购、架构与融资的一切，还必须运转起来：生产、贸易、支付、合规、存在——在法律、税务与运营层面皆然。"),
 "continuity": T("This door is not a change of subject — it is the continuity of the same structure. When an asset does not end at the sale, XARU can help structure its exploitation, commercialization, financial infrastructure and market access; and when an owner or a company must establish internationally, XARU builds the corporate, fiscal and family structure that lets the operation stand.",
           "Esta puerta no es un cambio de tema — es la continuidad de la misma estructura. Cuando un activo no termina en la compraventa, XARU puede ayudar a estructurar su explotación, comercialización, infraestructura financiera y acceso a mercado; y cuando un propietario o una compañía debe establecerse internacionalmente, XARU construye la estructura corporativa, fiscal y familiar que permite que la operación se sostenga.",
           "هذا الباب ليس تغييراً للموضوع — بل استمرارية البنية نفسها. عندما لا ينتهي الأصل عند البيع والشراء، يمكن أن تساعد XARU في هيكلة استغلاله وتسويقه وبنيته المالية ووصوله إلى السوق؛ وعندما يتعيّن على مالك أو شركة التأسيس دولياً، تبني XARU البنية المؤسسية والضريبية والعائلية التي تُبقي العملية قائمة.",
           "这扇门并非话题的转换——而是同一架构的延续。当一项资产并不止步于买卖，XARU 可协助架构其开发利用、商业化、金融基础设施与市场准入；当业主或企业需要国际化落地时，XARU 构建让运营得以立足的公司、税务与家庭架构。"),
 "trade_eyebrow": T("Division 6", "División 6", "القسم 6", "第六板块"),
 "trade_title": T("Trade & Financial Infrastructure", "Comercio e Infraestructura Financiera", "التجارة والبنية المالية", "贸易与金融基础设施"),
 "trade_lead": T("Productive assets and commodities — licences, production, offtake, placement — and the financial and technological infrastructure designed, integrated and coordinated with authorised entities and providers where the activity requires it.",
                 "Activos productivos y commodities — licencias, producción, offtake, colocación — y la infraestructura financiera y tecnológica diseñada, integrada y coordinada con entidades y proveedores autorizados cuando la actividad lo requiere.",
                 "الأصول الإنتاجية والسلع — التراخيص والإنتاج واتفاقيات الشراء المسبق والتصريف — والبنية المالية والتقنية المصمَّمة والمدمَجة والمنسَّقة مع كيانات ومزوّدين مرخّصين عندما يستلزم النشاط ذلك.",
                 "生产性资产与大宗商品——许可、产量、承购、配售——以及在业务需要时与获授权实体及服务商共同设计、整合与协调的金融与技术基础设施。"),
 "corp_eyebrow": T("Division 7", "División 7", "القسم 7", "第七板块"),
 "corp_title": T("Corporate Services & Relocation", "Servicios Corporativos y Relocalización", "الخدمات المؤسسية والانتقال", "企业服务与迁居"),
 "corp_lead": T("The full establishment cycle — company, government, tax, accounting, compliance, banking, operation, residency, family, continuity — provided directly or coordinated by jurisdiction, with specialised legal counsel in each one.",
                "El ciclo completo de establecimiento — empresa, gobierno, fiscalidad, contabilidad, cumplimiento, banca, operación, residencia, familia, continuidad — prestado directamente o coordinado según la jurisdicción, con asesoría legal especializada en cada una.",
                "دورة التأسيس الكاملة — الشركة والحوكمة والضرائب والمحاسبة والامتثال والمصارف والتشغيل والإقامة والعائلة والاستمرارية — تُقدَّم مباشرةً أو بالتنسيق بحسب الولاية القضائية، مع مستشارين قانونيين متخصّصين في كل منها.",
                "完整的落地周期——公司、治理、税务、会计、合规、银行、运营、居留、家庭、延续——视司法管辖区直接提供或协调完成，并在每个司法管辖区配有专业法律顾问。"),
 "view_division": T("View the division", "Ver la división", "عرض القسم", "查看板块"),
 "gov_eyebrow": T("Governance & standards", "Gobernanza y estándares", "الحوكمة والمعايير", "治理与标准"),
 "gov_title": T("The same rules, at the foundations", "Las mismas reglas, en los cimientos", "القواعد نفسها في الأساسات", "同样的规则，贯彻至基石"),
 "gov_lead": T("Business infrastructure runs under the same governance as every XARU mandate: confidentiality, due diligence, KYC / AML through regulated channels where applicable, and a defined scope in every jurisdiction. Compliance and corporate standards are described under Company.",
               "La infraestructura empresarial se rige por la misma gobernanza que todo mandato de XARU: confidencialidad, due diligence, KYC / AML por canales regulados cuando corresponda, y un alcance definido en cada jurisdicción. El cumplimiento y los estándares corporativos se describen en Compañía.",
               "تعمل البنية المؤسسية وفق الحوكمة ذاتها في كل تفويض لدى XARU: السرّية والعناية الواجبة واعرف عميلك / مكافحة الغسل عبر قنوات منظّمة عند الاقتضاء ونطاق محدّد في كل ولاية قضائية. يُعرض الامتثال والمعايير المؤسسية ضمن صفحة الشركة.",
               "企业基础设施遵循 XARU 每项委托同样的治理：保密、尽职调查、适用时通过受监管渠道进行 KYC / AML，以及在每个司法管辖区界定明确的范围。合规与公司标准详见「公司」页面。"),
 "gov_link1": T("Governance & standards — Company", "Gobernanza y estándares — Compañía", "الحوكمة والمعايير — الشركة", "治理与标准——公司"),
 "gov_link2": T("Entities & scope — Company", "Entidades y alcance — Compañía", "الكيانات والنطاق — الشركة", "实体与范围——公司"),
}
