# -*- coding: utf-8 -*-
"""XARU HOME — Phase 5 copy (institutional trust).
COMPANY page + INSIGHTS hub, in EN/ES/AR/ZH. Consumed by gen_i18n.py.
Rules (DERROTERO §3/§7/§8):
· Mandatory legal ambiguity — "XARU HOME operates under NEXARU GLOBAL, licensed
  in the United Arab Emirates. Regulated activities are provided through the
  corresponding entities or authorised partners in each jurisdiction." NEVER a
  licence number, never a full legal entity name, never an unverified claim.
· Corporate values of XARU are NOT the five ASHIMA pillars — the pillars
  (health, culture, eco, innovation, sustainability) are the narrative of the
  ASHIMA project and are labelled as such.
· Power is demonstrated (process, governance, cases), never declared.
· [PHASE 0] marks data pending verification — discreet, never invented.
· Brand names are never translated."""

def T(en, es, ar, zh):
    return {"en": en, "es": es, "ar": ar, "zh": zh}

# ================================================================ COMPANY
COMPANY = {

 "eyebrow": T("The Company", "La Compañía", "الشركة", "公司"),
 "title": T("Company", "Compañía", "الشركة", "公司"),

 "intro": T("From the asset to the operation — one responsible structure.",
            "Del activo a la operación — una sola estructura responsable.",
            "من الأصل إلى التشغيل — بنية مسؤولة واحدة.",
            "从资产到运营——唯一担责的架构。"),
 "intro_sub": T("XARU HOME is an international structure for real estate, development and business solutions. This page states who we are, how we operate, under which entities, and to which standards — so that trust rests on what can be verified.",
                "XARU HOME es una estructura internacional de real estate, desarrollo y soluciones empresariales. Esta página establece quiénes somos, cómo operamos, bajo qué entidades y con qué estándares — para que la confianza descanse en lo verificable.",
                "XARU HOME بنية دولية للعقارات والتطوير وحلول الأعمال. تعرض هذه الصفحة من نحن، وكيف نعمل، وتحت أي كيانات، ووفق أي معايير — لكي تقوم الثقة على ما يمكن التحقّق منه.",
                "XARU HOME 是一个覆盖房地产、开发与商业解决方案的国际架构。本页说明我们是谁、如何运作、隶属哪些实体、恪守何种标准——让信任建立在可核验的事实之上。"),

 # ---------------------------------------------------------------- Who we are
 "who_eyebrow": T("Who we are", "Quiénes somos", "من نحن", "关于我们"),
 "who_title": T("Three levels, one structure", "Tres niveles, una sola estructura", "ثلاثة مستويات وبنية واحدة", "三个层级，一个架构"),
 "who_lead": T("XARU HOME is understood in three levels — in this order.",
               "XARU HOME se entiende en tres niveles — en este orden.",
               "تُفهَم XARU HOME على ثلاثة مستويات — بهذا الترتيب.",
               "理解 XARU HOME，需依次看三个层级。"),
 "who_levels": [
   (T("The door", "La puerta", "الباب", "门"),
    T("An international real estate firm, clear and recognisable — exceptional properties, verified mandates, discreet intermediation.",
      "Una inmobiliaria internacional clara y reconocible — propiedades excepcionales, mandatos verificados, intermediación discreta.",
      "شركة عقارية دولية واضحة ومعروفة — عقارات استثنائية وتفويضات موثّقة ووساطة رصينة.",
      "一家清晰可辨的国际房地产公司——卓越房产、经核实的委托、审慎的中介。")),
   (T("The building", "El edificio", "المبنى", "楼"),
    T("A structure able to develop, finance and execute projects — land, master developments, structuring and capital, under one responsibility.",
      "Una estructura capaz de desarrollar, financiar y ejecutar proyectos — suelo, desarrollos maestros, estructuración y capital, bajo una sola responsabilidad.",
      "بنية قادرة على تطوير المشاريع وتمويلها وتنفيذها — الأراضي والتطويرات الكبرى والهيكلة ورأس المال، تحت مسؤولية واحدة.",
      "一个能够开发、融资并执行项目的架构——土地、总体开发、架构设计与资本，统一担责。")),
   (T("The foundations", "Los cimientos", "الأساسات", "基石"),
    T("A business platform that sustains operation, trade, technology, compliance and international establishment — so that what is acquired also works.",
      "Una plataforma empresarial que soporta operación, comercio, tecnología, cumplimiento y establecimiento internacional — para que lo adquirido también funcione.",
      "منصّة أعمال تسند التشغيل والتجارة والتقنية والامتثال والتأسيس الدولي — لكي يعمل ما تم اقتناؤه أيضاً.",
      "一个支撑运营、贸易、技术、合规与国际落地的商业平台——让所购得的一切真正运转。")),
 ],
 "who_phrase": T("“From the asset to the operation, one responsible structure.”",
                 "«Del activo a la operación, una sola estructura responsable.»",
                 "«من الأصل إلى التشغيل، بنية مسؤولة واحدة.»",
                 "「从资产到运营，唯一担责的架构。」"),

 # ---------------------------------------------------------------- Corporate values
 "val_eyebrow": T("Corporate values", "Valores corporativos", "القيم المؤسسية", "企业价值观"),
 "val_title": T("What governs XARU — in every mandate", "Lo que rige a XARU — en cada mandato", "ما يحكم XARU — في كل تفويض", "XARU 的准则——贯穿每项委托"),
 "values": [
   (T("Stewardship", "Protección patrimonial", "رعاية الثروة", "资产守护"),
    T("Every asset, project and family is treated as patrimony under care — never as inventory.",
      "Cada activo, proyecto y familia se trata como patrimonio bajo custodia — nunca como inventario.",
      "يُعامَل كل أصل ومشروع وعائلة كثروة تحت الرعاية — لا كمخزون أبداً.",
      "每项资产、每个项目、每个家庭，皆作为受托守护的财富对待——绝非库存。")),
   (T("One responsibility", "Una sola responsabilidad", "مسؤولية واحدة", "统一担责"),
    T("One structure answers for the whole route — no hand-offs, no diluted accountability.",
      "Una sola estructura responde por toda la ruta — sin traspasos, sin responsabilidad diluida.",
      "بنية واحدة تتحمّل المسؤولية عن المسار كله — دون تسليمات متتابعة ولا مسؤولية مميّعة.",
      "由一个架构对全程负责——不层层转手，不稀释责任。")),
   (T("Confidentiality", "Confidencialidad", "السرّية", "保密"),
    T("Discretion is a working method: teasers without sensitive data, NDA before disclosure, private channels.",
      "La discreción es un método de trabajo: teasers sin datos sensibles, NDA antes de revelar, canales privados.",
      "التحفّظ منهج عمل: موجزات دون بيانات حسّاسة، واتفاقية سرّية قبل أي إفصاح، وقنوات خاصة.",
      "审慎是一种工作方法：不含敏感数据的简报、披露前的保密协议、私密渠道。")),
   (T("Rigour & compliance", "Rigor y cumplimiento", "الانضباط والامتثال", "严谨与合规"),
    T("Verification before publication; KYC / AML through regulated channels where applicable; nothing affirmed that has not been verified.",
      "Verificación antes de publicar; KYC / AML por canales regulados cuando corresponde; nada se afirma sin verificar.",
      "التحقّق قبل النشر؛ واعرف عميلك / مكافحة الغسل عبر قنوات منظّمة عند الاقتضاء؛ ولا يُؤكَّد شيء لم يُتحقَّق منه.",
      "先核实、后发布；适用时通过受监管渠道进行 KYC / AML；未经核实之事，绝不宣称。")),
   (T("Continuity", "Continuidad", "الاستمرارية", "延续"),
    T("XARU remains after the transaction — operation, administration and follow-through, year after year.",
      "XARU permanece después de la transacción — operación, administración y seguimiento, año tras año.",
      "تبقى XARU بعد الصفقة — تشغيلاً وإدارةً ومتابعةً، عاماً بعد عام.",
      "交易之后，XARU 仍在——运营、管理与跟进，年复一年。")),
 ],
 "val_note": T("A distinction we keep deliberately: health and wellness, ancestral culture, eco-friendly practice, innovation and sustainable development are the five narrative pillars of the ASHIMA project — the language of one signature development. The values above are the corporate values of XARU HOME itself.",
               "Una distinción que mantenemos deliberadamente: salud y bienestar, cultura ancestral, práctica ecológica, innovación y desarrollo sostenible son los cinco pilares narrativos del proyecto ASHIMA — el lenguaje de un desarrollo emblemático. Los valores anteriores son los valores corporativos de XARU HOME.",
               "تمييز نحافظ عليه عن قصد: الصحة والعافية، والثقافة الأصيلة، والممارسة البيئية، والابتكار، والتنمية المستدامة هي الركائز السردية الخمس لمشروع ASHIMA — لغة مشروع تطويري مميّز. أمّا القيم أعلاه فهي القيم المؤسسية لـ XARU HOME نفسها.",
               "我们刻意保持一项区分：健康养生、祖源文化、生态实践、创新与可持续发展，是 ASHIMA 项目的五大叙事支柱——属于一个标志性开发项目的语言。上述价值观才是 XARU HOME 自身的企业价值观。"),

 # ---------------------------------------------------------------- Operating model
 "model_eyebrow": T("Operating model", "Modelo operativo", "نموذج التشغيل", "运营模式"),
 "model_title": T("One umbrella, seven autonomous divisions", "Un solo paraguas, siete divisiones autónomas", "مظلّة واحدة وسبعة أقسام مستقلّة", "一把大伞，七个自主板块"),
 "model_lead": T("XARU HOME operates as a single umbrella under which seven specialised divisions work with their own discipline, their own admission criteria and their own processes — and hand a mandate to each other without the client ever leaving the structure. The client speaks with one responsible desk; the structure routes the work.",
                 "XARU HOME opera como un solo paraguas bajo el cual siete divisiones especializadas trabajan con su propia disciplina, sus propios criterios de admisión y sus propios procesos — y se pasan un mandato entre sí sin que el cliente salga jamás de la estructura. El cliente habla con una sola mesa responsable; la estructura enruta el trabajo.",
                 "تعمل XARU HOME كمظلّة واحدة تعمل تحتها سبعة أقسام متخصّصة بانضباطها الخاص ومعايير قبولها وإجراءاتها — وتتناقل التفويض فيما بينها دون أن يغادر العميل البنية أبداً. يتحدّث العميل مع مكتب مسؤول واحد؛ والبنية توجّه العمل.",
                 "XARU HOME 以单一大伞运作：伞下七个专业板块各有其纪律、准入标准与流程——委托可在板块之间交接，而客户始终无需离开这一架构。客户只需面对一个负责的服务台；架构自会调度工作。"),
 "divisions": [
   ("real-estate/", T("Real Estate — private properties", "Real Estate — propiedades privadas", "العقارات — العقارات الخاصة", "房地产——私人房产")),
   ("real-estate/commercial-hospitality/", T("Commercial & Hospitality — operating assets", "Commercial & Hospitality — activos operativos", "التجاري والضيافة — الأصول التشغيلية", "商业与酒店——运营资产")),
   ("developments/land-master-developments/", T("Land & Master Developments", "Land & Master Developments", "الأراضي والتطويرات الكبرى", "土地与总体开发")),
   ("developments/project-structuring/", T("Project Structuring & Development", "Project Structuring & Development", "هيكلة وتطوير المشاريع", "项目架构与开发")),
   ("capital/strategic-partnerships/", T("Capital & Strategic Partnerships", "Capital & Strategic Partnerships", "رأس المال والشراكات الاستراتيجية", "资本与战略合作")),
   ("business-infrastructure/trade-financial/", T("Trade & Financial Infrastructure", "Trade & Financial Infrastructure", "التجارة والبنية المالية", "贸易与金融基础设施")),
   ("business-infrastructure/corporate-services/", T("Corporate Services & Relocation", "Corporate Services & Relocation", "الخدمات المؤسسية والانتقال", "企业服务与迁居")),
 ],

 # ---------------------------------------------------------------- Offices
 "off_eyebrow": T("Offices", "Oficinas", "المكاتب", "办公网络"),
 "off_title": T("Where XARU stands", "Dónde está XARU", "أين تقف XARU", "XARU 立足之地"),
 "off_hq_city": T("Dubai, United Arab Emirates", "Dubái, Emiratos Árabes Unidos", "دبي، الإمارات العربية المتحدة", "迪拜，阿拉伯联合酋长国"),
 "off_hq_tag": T("Headquarters", "Sede", "المقر الرئيسي", "总部"),
 "off_hq_desc": T("The operating base of the structure — where mandates are admitted, coordinated and answered for.",
                  "La base operativa de la estructura — donde los mandatos se admiten, se coordinan y se responden.",
                  "القاعدة التشغيلية للبنية — حيث تُقبل التفويضات وتُنسَّق ويُجاب عنها.",
                  "架构的运营基地——委托在此受理、协调并得到回应。"),
 "off_more_h": T("Additional locations", "Otras ubicaciones", "مواقع إضافية", "其他驻地"),
 "off_more_p": T("Further offices and representations across the network's regions are published as they are verified.",
                 "Otras oficinas y representaciones en las regiones de la red se publican a medida que se verifican.",
                 "تُنشر المكاتب والتمثيلات الأخرى في مناطق الشبكة تباعاً بعد التحقّق منها.",
                 "网络所覆盖地区的其他办公室与代表处，将在核实后陆续公布。"),

 # ---------------------------------------------------------------- Team
 "team_eyebrow": T("Team", "Equipo", "الفريق", "团队"),
 "team_title": T("Specialities, not titles", "Especialidades, no títulos", "تخصّصات لا ألقاب", "专业领域，而非头衔"),
 "team_lead": T("The structure is staffed by areas of specialty. Every mandate is carried by the disciplines it requires — coordinated under one responsible desk.",
                "La estructura se compone por áreas de especialidad. Cada mandato lo llevan las disciplinas que requiere — coordinadas bajo una sola mesa responsable.",
                "تتكوّن البنية من مجالات تخصّص. وكل تفويض تتولاه التخصّصات التي يتطلّبها — بتنسيق مكتب مسؤول واحد.",
                "架构按专业领域组建。每项委托由其所需的各专业承担——统一在一个负责服务台之下协调。"),
 "team_areas": [
   (T("Legal", "Legal", "القانوني", "法律"),
    T("Structuring, mandates, contracts — with specialised counsel in each jurisdiction.",
      "Estructuración, mandatos, contratos — con asesoría especializada en cada jurisdicción.",
      "الهيكلة والتفويضات والعقود — مع مستشارين متخصّصين في كل ولاية قضائية.",
      "架构、委托与合同——与各司法管辖区的专业顾问协同。")),
   (T("Tax", "Fiscal", "الضريبي", "税务"),
    T("Regime, substance and cross-border coordination by jurisdiction.",
      "Régimen, sustancia y coordinación transfronteriza por jurisdicción.",
      "النظام الضريبي والجوهر والتنسيق العابر للحدود بحسب الولاية القضائية.",
      "按司法管辖区统筹税制、实质与跨境协调。")),
   (T("Accounting", "Contable", "المحاسبي", "会计"),
    T("Books, audit and reporting for structures and operations.",
      "Libros, auditoría y reporting para estructuras y operaciones.",
      "الدفاتر والتدقيق والتقارير للبنى والعمليات.",
      "为架构与运营提供账簿、审计与申报。")),
   (T("Compliance", "Cumplimiento", "الامتثال", "合规"),
    T("AML, due diligence, KYC through regulated channels where applicable.",
      "AML, due diligence, KYC por canales regulados cuando corresponde.",
      "مكافحة الغسل والعناية الواجبة واعرف عميلك عبر قنوات منظّمة عند الاقتضاء.",
      "反洗钱、尽职调查，适用时经受监管渠道进行 KYC。")),
   (T("Development", "Desarrollo", "التطوير", "开发"),
    T("Feasibility, master planning, development management and delivery.",
      "Viabilidad, master planning, gestión de desarrollo y entrega.",
      "الجدوى والتخطيط العام وإدارة التطوير والتسليم.",
      "可行性、总体规划、开发管理与交付。")),
   (T("Commercial", "Comercial", "التجاري", "商业"),
    T("Mandates, counterparties, placement and transaction management.",
      "Mandatos, contrapartes, colocación y gestión de transacciones.",
      "التفويضات والأطراف المقابلة والتصريف وإدارة الصفقات.",
      "委托、对手方、配售与交易管理。")),
   (T("Technology", "Tecnología", "التقنية", "技术"),
    T("Platforms, integrations and financial-infrastructure engineering.",
      "Plataformas, integraciones e ingeniería de infraestructura financiera.",
      "المنصّات والتكاملات وهندسة البنية المالية.",
      "平台、集成与金融基础设施工程。")),
 ],
 "team_note": T("Partner and team profiles are published upon verification.",
                "Los perfiles de socios y equipo se publican una vez verificados.",
                "تُنشر ملفات الشركاء والفريق بعد التحقّق منها.",
                "合伙人与团队简介经核实后发布。"),

 # ---------------------------------------------------------------- Entities & scope (MANDATORY AMBIGUITY)
 "ent_eyebrow": T("Entities & scope", "Entidades y alcance", "الكيانات والنطاق", "实体与范围"),
 "ent_title": T("Under which structure XARU operates", "Bajo qué estructura opera XARU", "تحت أي بنية تعمل XARU", "XARU 在何种架构下运营"),
 "ent_main": T("XARU HOME operates under NEXARU GLOBAL, licensed in the United Arab Emirates. Regulated activities are provided through the corresponding entities or authorised partners in each jurisdiction.",
               "XARU HOME opera bajo NEXARU GLOBAL, con licencia en Emiratos Árabes Unidos. Las actividades reguladas se prestan a través de las entidades correspondientes o de partners autorizados en cada jurisdicción.",
               "تعمل XARU HOME تحت NEXARU GLOBAL، المرخّصة في الإمارات العربية المتحدة. وتُقدَّم الأنشطة الخاضعة للتنظيم عبر الكيانات المعنيّة أو الشركاء المرخّصين في كل ولاية قضائية.",
               "XARU HOME 隶属于 NEXARU GLOBAL 运营，后者持有阿拉伯联合酋长国牌照。受监管的业务经由相应实体或各司法管辖区的获授权合作伙伴提供。"),
 "ent_sub": T("Every proposal states, in writing, which entity or partner acts, in which jurisdiction and in which capacity. What cannot be stated in writing is not offered.",
              "Cada propuesta establece por escrito qué entidad o partner actúa, en qué jurisdicción y en qué capacidad. Lo que no puede establecerse por escrito, no se ofrece.",
              "يحدّد كل عرض كتابةً أي كيان أو شريك يتصرّف، وفي أي ولاية قضائية، وبأي صفة. وما لا يمكن إثباته كتابةً لا يُعرَض.",
              "每份提案均以书面明确由哪一实体或合作伙伴、在哪个司法管辖区、以何种身份行事。凡无法以书面确立者，概不提供。"),

 # ---------------------------------------------------------------- Governance & standards
 "gov_eyebrow": T("Governance & standards", "Gobernanza y estándares", "الحوكمة والمعايير", "治理与标准"),
 "gov_title": T("Power is demonstrated, not declared", "El poder se demuestra, no se declara", "القوة تُبرهَن لا تُعلَن", "实力以行动证明，而非声称"),
 "gov_lead": T("Every XARU mandate — residential, territorial, capital or corporate — runs under the same standards:",
               "Todo mandato de XARU — residencial, territorial, de capital o corporativo — se rige por los mismos estándares:",
               "كل تفويض لدى XARU — سكنياً كان أو إقليمياً أو رأسمالياً أو مؤسسياً — يخضع للمعايير ذاتها:",
               "XARU 的每项委托——无论住宅、土地、资本或企业——都遵循同一套标准："),
 "gov_items": [
   T("Confidentiality as method — teasers without sensitive data; disclosure only under NDA",
     "Confidencialidad como método — teasers sin datos sensibles; revelación solo bajo NDA",
     "السرّية منهجاً — موجزات دون بيانات حسّاسة، وإفصاح بموجب اتفاقية سرّية فقط",
     "以保密为方法——简报不含敏感数据；仅在保密协议下披露"),
   T("Due diligence and verified mandates before anything is published",
     "Due diligence y mandatos verificados antes de publicar nada",
     "العناية الواجبة والتفويضات الموثّقة قبل نشر أي شيء",
     "先尽调、先核实委托，而后才有任何发布"),
   T("KYC / AML through regulated channels where the activity requires it",
     "KYC / AML por canales regulados cuando la actividad lo requiere",
     "اعرف عميلك / مكافحة الغسل عبر قنوات منظّمة عندما يستلزم النشاط ذلك",
     "业务需要时，通过受监管渠道进行 KYC / AML"),
   T("Information protection — owners, coordinates, financials and licences are never exposed",
     "Protección de la información — propietarios, coordenadas, finanzas y licencias nunca se exponen",
     "حماية المعلومات — لا تُكشف هويات الملّاك ولا الإحداثيات ولا البيانات المالية ولا التراخيص أبداً",
     "信息保护——业主、坐标、财务与许可永不暴露"),
   T("Legal and tax coordination with specialised counsel in each jurisdiction",
     "Coordinación legal y fiscal con asesoría especializada en cada jurisdicción",
     "تنسيق قانوني وضريبي مع مستشارين متخصّصين في كل ولاية قضائية",
     "与各司法管辖区的专业顾问进行法律与税务协调"),
   T("A defined regulatory scope — regulated services through authorised entities and partners, stated in writing",
     "Un alcance regulatorio definido — servicios regulados a través de entidades y partners autorizados, establecido por escrito",
     "نطاق تنظيمي محدّد — خدمات منظّمة عبر كيانات وشركاء مرخّصين، مُثبَت كتابةً",
     "界定明确的监管范围——受监管服务经获授权实体与合作伙伴提供，并以书面载明"),
   T("Documented sequence in every process — intake, verification, NDA, review, execution, follow-through",
     "Secuencia documentada en cada proceso — intake, verificación, NDA, revisión, ejecución, seguimiento",
     "تسلسل موثَّق في كل إجراء — الاستقبال والتحقّق واتفاقية السرّية والمراجعة والتنفيذ والمتابعة",
     "每个流程都有可查的顺序——受理、核实、保密协议、审查、执行、跟进"),
 ],

 # ---------------------------------------------------------------- Projects & cases
 "proj_eyebrow": T("Projects & cases", "Proyectos y casos", "المشاريع والحالات", "项目与案例"),
 "proj_title": T("Cases, correctly classified", "Casos, correctamente clasificados", "حالات مصنّفة تصنيفاً صحيحاً", "案例，如实归类"),
 "proj_lead": T("XARU publishes cases as what they are — never more. A project in structuring is presented as in structuring; a halted asset as halted; a confidential mandate stays confidential.",
                "XARU publica los casos como lo que son — nunca más. Un proyecto en estructuración se presenta en estructuración; un activo detenido, como detenido; un mandato confidencial permanece confidencial.",
                "تنشر XARU الحالات كما هي — لا أكثر أبداً. فالمشروع قيد الهيكلة يُعرَض قيد الهيكلة؛ والأصل المتوقف يُعرَض متوقفاً؛ والتفويض السرّي يبقى سرّياً.",
                "XARU 按事实呈现案例——绝不夸大。架构中的项目就标注为架构中；停滞的资产就标注为停滞；保密的委托始终保密。"),
 "ashima_tag": T("Signature case — master development, in structuring",
                 "Caso emblemático — desarrollo maestro, en estructuración",
                 "حالة مميّزة — تطوير كبير، قيد الهيكلة",
                 "标志性案例——总体开发，架构中"),
 "ashima_h": T("ASHIMA — Ancestral Odyssey · Oaxaca, México",
               "ASHIMA — Odisea ancestral · Oaxaca, México",
               "ASHIMA — أوديسة الأجداد · واهاكا، المكسيك",
               "ASHIMA——祖源奥德赛 · 墨西哥瓦哈卡"),
 "ashima_p": T("A territorial project conceived as a destination: coastal territory, phased master plan, its own cultural and ecological narrative — the five ASHIMA pillars — and a structuring discipline that separates vision from execution stages. ASHIMA shows how XARU works at scale: governance first, then drawings.",
               "Un proyecto territorial concebido como destino: territorio costero, master plan por fases, una narrativa cultural y ecológica propia — los cinco pilares de ASHIMA — y una disciplina de estructuración que separa la visión de las etapas de ejecución. ASHIMA muestra cómo trabaja XARU a escala: primero la gobernanza, después los planos.",
               "مشروع إقليمي صُمِّم كوجهة: أرض ساحلية، ومخطط عام على مراحل، وسردية ثقافية وبيئية خاصة به — ركائز ASHIMA الخمس — وانضباط هيكلة يفصل الرؤية عن مراحل التنفيذ. تُظهر ASHIMA كيف تعمل XARU على نطاق واسع: الحوكمة أولاً، ثم المخططات.",
               "一个以目的地为构想的土地项目：滨海土地、分期总体规划、自成一体的文化与生态叙事——即 ASHIMA 的五大支柱——以及将愿景与执行阶段分开的架构纪律。ASHIMA 展示了 XARU 的大尺度工作方式：治理先行，图纸在后。"),
 "ashima_cta": T("View the division", "Ver la división", "عرض القسم", "查看板块"),
 "proj_more_h": T("Further cases", "Otros casos", "حالات أخرى", "更多案例"),
 "proj_more_p": T("Additional cases are published as mandates and confidentiality allow. Confidential situations live in the Private Deal Room.",
                  "Otros casos se publican a medida que los mandatos y la confidencialidad lo permiten. Las situaciones confidenciales viven en el Private Deal Room.",
                  "تُنشر حالات إضافية بقدر ما تسمح به التفويضات والسرّية. أمّا الحالات السرّية فمكانها غرفة الصفقات الخاصة.",
                  "更多案例将在委托与保密条件允许时发布。保密事项一律置于私人交易室。"),
 "proj_more_cta": T("Private Deal Room", "Private Deal Room", "غرفة الصفقات الخاصة", "私人交易室"),

 # ---------------------------------------------------------------- International network
 "net_eyebrow": T("International network", "Red internacional", "الشبكة الدولية", "国际网络"),
 "net_title": T("Own network and strategic allies", "Red propia y aliados estratégicos", "شبكة خاصة وحلفاء استراتيجيون", "自有网络与战略盟友"),
 "net_lead": T("XARU serves its markets through its own structure and through strategic allies established in each region. Presence today spans:",
               "XARU atiende sus mercados a través de su propia estructura y de aliados estratégicos establecidos en cada región. La presencia abarca hoy:",
               "تخدم XARU أسواقها عبر بنيتها الخاصة وعبر حلفاء استراتيجيين راسخين في كل منطقة. ويمتد الحضور اليوم عبر:",
               "XARU 通过自有架构及扎根各地区的战略盟友服务其市场。目前的布局覆盖："),
 "net_regions": [
   T("United Arab Emirates & Middle East", "Emiratos Árabes Unidos y Medio Oriente", "الإمارات العربية المتحدة والشرق الأوسط", "阿联酋与中东"),
   T("China", "China", "الصين", "中国"),
   T("India", "India", "الهند", "印度"),
   T("Pakistan", "Pakistán", "باكستان", "巴基斯坦"),
   T("Europe", "Europa", "أوروبا", "欧洲"),
   T("United States", "Estados Unidos", "الولايات المتحدة", "美国"),
   T("Latin America", "Latinoamérica", "أمريكا اللاتينية", "拉丁美洲"),
 ],
 "net_note": T("In each region, services are provided directly or with allied firms — always under the governance described above.",
               "En cada región, los servicios se prestan directamente o con firmas aliadas — siempre bajo la gobernanza descrita arriba.",
               "في كل منطقة، تُقدَّم الخدمات مباشرةً أو مع شركات حليفة — ودائماً وفق الحوكمة الموضّحة أعلاه.",
               "在每个地区，服务由自身或盟友机构提供——始终遵循上述治理准则。"),

 # ---------------------------------------------------------------- CTA
 "cta_eyebrow": T("Private Desk", "Mesa Privada", "المكتب الخاص", "私人服务台"),
 "cta_title": T("One conversation. One structure. Total confidentiality.",
                "Una conversación. Una estructura. Total confidencialidad.",
                "محادثة واحدة. بنية واحدة. سرّية تامّة.",
                "一次对话。单一架构。全然保密。"),
 "cta_btn": T("Private Enquiry", "Consulta Privada", "استفسار خاص", "私人咨询"),
 "cta_btn2": T("Submit an Opportunity", "Presentar una oportunidad", "تقديم فرصة", "提交机会"),
}

# ================================================================ INSIGHTS hub
INSIGHTS = {
 "eyebrow": T("Insights", "Análisis", "رؤى", "洞察"),
 "title": T("Insights", "Análisis", "رؤى", "洞察"),
 "intro": T("Analysis from the operating table.", "Análisis desde la mesa de operaciones.", "تحليل من طاولة العمليات.", "来自交易一线的分析。"),
 "intro_sub": T("Sector by sector, written by the structure that executes — patrimonial in tone, qualitative in claim, and free of numbers that cannot be defended.",
                "Sector por sector, escrito por la estructura que ejecuta — de tono patrimonial, cualitativo en sus afirmaciones y libre de cifras que no puedan defenderse.",
                "قطاعاً بقطاع، بقلم البنية التي تنفّذ — بنبرة ثروية، وبطرح نوعي، ومن دون أرقام لا يمكن الدفاع عنها.",
                "逐一剖析各个板块，由亲身执行的架构撰写——笔调稳重，立论以定性为本，不使用无法佐证的数字。"),
 "byline": T("XARU HOME Research", "XARU HOME Research", "XARU HOME Research", "XARU HOME Research"),
 "read": T("Read the analysis", "Leer el análisis", "اقرأ التحليل", "阅读分析"),
 "soon": T("Research in preparation", "Análisis en preparación", "بحث قيد الإعداد", "研究筹备中"),
 "cats_eyebrow": T("Sectors", "Sectores", "القطاعات", "板块"),
 "cats_title": T("Seven sectors, one discipline", "Siete sectores, una sola disciplina", "سبعة قطاعات وانضباط واحد", "七个板块，同一纪律"),
 "found_eyebrow": T("Foundational analyses", "Análisis fundacionales", "تحليلات تأسيسية", "奠基分析"),
 "found_title": T("The first four", "Los primeros cuatro", "الأربعة الأولى", "首批四篇"),
 "back": T("All insights", "Todos los análisis", "جميع الرؤى", "全部洞察"),

 # (anchor-slug, label, blurb, article-key or None, hero img)
 "categories": [
  ("luxury-residential",
   T("Luxury residential", "Residencial de lujo", "السكني الفاخر", "奢华住宅"),
   T("Exceptional homes, islands and estates — where patrimony and lifestyle meet.",
     "Residencias excepcionales, islas y fincas — donde patrimonio y estilo de vida se encuentran.",
     "مساكن استثنائية وجزر وضياع — حيث تلتقي الثروة بأسلوب الحياة.",
     "卓越宅邸、岛屿与庄园——财富与生活方式的交汇处。"), None),
  ("hospitality",
   T("Hospitality", "Hostelería", "الضيافة", "酒店业"),
   T("Operating hotels, resorts and serviced assets — priced on their P&L, not their postcard.",
     "Hoteles, resorts y activos en operación — valorados por su P&L, no por su postal.",
     "فنادق ومنتجعات وأصول تشغيلية — تُقيَّم بحساب أرباحها وخسائرها لا بصورتها.",
     "运营中的酒店、度假村与服务式资产——以损益表定价，而非以风景明信片。"), "operational-hospitality"),
  ("land",
   T("Land", "Suelo", "الأراضي", "土地"),
   T("Territory, tenure and the thesis of scale — from parcels to destinations.",
     "Territorio, tenencia y la tesis de la escala — de parcelas a destinos.",
     "الأرض والحيازة وأطروحة الحجم — من القطع إلى الوجهات.",
     "土地、权属与规模命题——从地块到目的地。"), "territorial-land"),
  ("capital",
   T("Capital", "Capital", "رأس المال", "资本"),
   T("Private capital, restructuring and the two-way table between projects and funding.",
     "Capital privado, reestructuración y la doble vía entre proyectos y financiación.",
     "رأس المال الخاص وإعادة الهيكلة والمسار الثنائي بين المشاريع والتمويل.",
     "私人资本、重组，以及项目与资金之间的双向通道。"), "capital-halted-projects"),
  ("development",
   T("Development", "Desarrollo", "التطوير", "开发"),
   T("Structuring, master planning and delivery — governance before drawings.",
     "Estructuración, master planning y entrega — gobernanza antes que planos.",
     "الهيكلة والتخطيط العام والتسليم — الحوكمة قبل المخططات.",
     "架构、总体规划与交付——治理先于图纸。"), None),
  ("commodities",
   T("Commodities", "Commodities", "السلع", "大宗商品"),
   T("Productive assets, offtake and placement — the operation after the transaction.",
     "Activos productivos, offtake y colocación — la operación después de la transacción.",
     "الأصول الإنتاجية واتفاقيات الشراء المسبق والتصريف — التشغيل بعد الصفقة.",
     "生产性资产、承购与配售——交易之后的运营。"), None),
  ("international-establishment",
   T("International establishment", "Establecimiento internacional", "التأسيس الدولي", "国际落地"),
   T("Entities, compliance, banking, residency — the structure behind a working presence.",
     "Entidades, cumplimiento, banca, residencia — la estructura detrás de una presencia operativa.",
     "الكيانات والامتثال والمصارف والإقامة — البنية وراء حضور فعّال.",
     "实体、合规、银行、居留——有效存在背后的架构。"), "international-establishment"),
 ],
}
