#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Firmador de peticiones a la API de Storyblocks para XARU HOME.

POR QUÉ EXISTE ESTE FICHERO
---------------------------
El contenedor donde corre el agente NO tiene salida a internet hacia
`api.storyblocks.com` (comprobado: la conexión muere en el proxy). Tampoco la
tiene `device_bash` en el Mac. El único proceso de toda la cadena que SÍ llega
a internet es **Chrome**.

Así que la petición se parte en dos mitades:

  1. AQUÍ (sin red): se construye y se FIRMA la URL. Firmar es sólo criptografía
     local — HMAC-SHA256 — así que no hace falta salir a ningún sitio.
  2. EN CHROME (con red): se navega a esa URL ya firmada. Para búsquedas, la
     respuesta es JSON y se lee del DOM. Para descargas, el fichero cae en
     ~/Downloads y se recoge con device_stage_files, igual que en las otras
     fuentes.

ESQUEMA DE AUTENTICACIÓN (documentación oficial de Storyblocks)
---------------------------------------------------------------
    "The authentication code is generated by using the SHA-256 hmac algorithm
     with the requested resource as the data and the secret key concatenated
     with the expiration time as the key."

  HMAC = HMAC_SHA256(clave = private_key + EXPIRES, mensaje = resource_path)

Parámetros obligatorios en toda petición: APIKEY, EXPIRES, HMAC, user_id,
project_id. EXPIRES es un timestamp Unix, como mucho 36 h en el futuro.

Importante: `resource_path` es la RUTA, sin dominio y sin query string.

CREDENCIALES
------------
Nunca van en el código ni en el chat. Se leen de un fichero en el Mac de Josep,
el mismo patrón que ya usamos para el token de GitHub:

    /Users/joseilc/XARU_HOME/.xaru_storyblocks.json

    {
      "api_key":     "...",
      "private_key": "...",
      "project_id":  "xaruhome",
      "user_id":     "..."
    }

Uso:
    python3 tools_storyblocks.py search "santorini caldera hotel" --page 1
    python3 tools_storyblocks.py download 123456789
    python3 tools_storyblocks.py search "villa" --creds /ruta/al/.xaru_storyblocks.json
"""

import argparse
import hashlib
import hmac
import json
import os
import sys
import time
import urllib.parse

BASE = "https://api.storyblocks.com"

# Rutas por convención de la API v2 de Storyblocks. La documentación pública no
# las publica; si alguna devuelve 404 se ajusta aquí en un sitio y ya está.
PATH_SEARCH_IMAGES = "/api/v2/images/search"
PATH_DOWNLOAD_IMAGE = "/api/v2/images/stock-item/download/%s"
PATH_SEARCH_VIDEOS = "/api/v2/videos/search"
PATH_DOWNLOAD_VIDEO = "/api/v2/videos/stock-item/download/%s"

DEFAULT_CREDS = "/Users/joseilc/XARU_HOME/.xaru_storyblocks.json"


def load_creds(path=None):
    """Carga las credenciales. Si no están, lo dice claro en vez de fallar raro."""
    path = path or os.environ.get("XARU_STORYBLOCKS_CREDS") or DEFAULT_CREDS
    if not os.path.exists(path):
        sys.exit(
            "No encuentro las credenciales en %s\n"
            "Crea ese fichero con: api_key, private_key, project_id, user_id.\n"
            "Nunca las pegues en el chat." % path
        )
    with open(path, encoding="utf-8") as f:
        c = json.load(f)
    missing = [k for k in ("api_key", "private_key", "project_id", "user_id") if not c.get(k)]
    if missing:
        sys.exit("Faltan claves en %s: %s" % (path, ", ".join(missing)))
    return c


def sign(resource_path, private_key, expires=None):
    """HMAC_SHA256(clave = private_key + expires, mensaje = resource_path)."""
    if expires is None:
        expires = int(time.time()) + 3000        # ~50 min; el tope son 36 h
    digest = hmac.new(
        (private_key + str(expires)).encode("utf-8"),
        resource_path.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()
    return digest, expires


def build_url(resource_path, creds, extra=None, expires=None):
    """Devuelve la URL completa y firmada, lista para que Chrome la navegue."""
    hm, exp = sign(resource_path, creds["private_key"], expires)
    params = {
        "APIKEY": creds["api_key"],
        "EXPIRES": exp,
        "HMAC": hm,
        "project_id": creds["project_id"],
        "user_id": creds["user_id"],
    }
    if extra:
        params.update({k: v for k, v in extra.items() if v not in (None, "")})
    return BASE + resource_path + "?" + urllib.parse.urlencode(params)


def cmd_search(a):
    creds = load_creds(a.creds)
    path = PATH_SEARCH_VIDEOS if a.videos else PATH_SEARCH_IMAGES
    extra = {
        "keywords": a.keywords,
        "page": a.page,
        "results_per_page": a.per_page,
        "content_type": a.content_type,
        "orientation": a.orientation,
        "sort_by": a.sort_by,
    }
    print(build_url(path, creds, extra))


def cmd_download(a):
    creds = load_creds(a.creds)
    tmpl = PATH_DOWNLOAD_VIDEO if a.videos else PATH_DOWNLOAD_IMAGE
    print(build_url(tmpl % a.stock_item_id, creds))


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--creds", help="ruta al JSON de credenciales")
    p.add_argument("--videos", action="store_true", help="usar los endpoints de vídeo")
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("search", help="imprime la URL firmada de búsqueda")
    s.add_argument("keywords")
    s.add_argument("--page", type=int, default=1)
    s.add_argument("--per-page", type=int, default=50, dest="per_page")
    s.add_argument("--content-type", dest="content_type", default=None)
    s.add_argument("--orientation", default=None)
    s.add_argument("--sort-by", dest="sort_by", default=None)
    s.set_defaults(func=cmd_search)

    d = sub.add_parser("download", help="imprime la URL firmada de descarga")
    d.add_argument("stock_item_id")
    d.set_defaults(func=cmd_download)

    a = p.parse_args()
    a.func(a)


if __name__ == "__main__":
    main()
